lnis-uofu/OpenFPGA

- README.md
* Make the compile steps easy to copy.
* Small wording fixes.
* Use relative links (github rewrites them).
* Remove unneeded `<br>` tags.
> Small formatting fixes to the README

- fpga_flow/configs/tutorial/tuto.conf
Fix paths in `tuto.conf` it looks like tang's absolute paths were accidentally committed.
> Fix tutorial configuration file

- Dockerfile
As documented in `OpenFPGA/tutorials/building.md` one should not run `make -j` in Docker as `errors will happen`.
> Fix docker file (do not run make multi threaded) 

- .travis.yml
- vpr7_x2p/vpr/CMakeLists.txt
Updated cmakelist to fix gui support with cmake > 3.12.  Tested on ubuntu 18.04, gcc8, cmake 3.16.3.
This is a hacky way to do it, but it works.
> Fix GUI support with cmake 3.16

- libopenfpga/libopenfpgashell/src/shell.tpp
- libopenfpga/libopenfpgautil/src/openfpga_digest.cpp
> Bug fix in the line parser when dealing with empty inputs for Centos 8 which is strict on this

- docs/source/manual/arch_lang/circuit_library.rst
- libopenfpga/libarchopenfpga/src/check_circuit_library.cpp
- libopenfpga/libarchopenfpga/src/circuit_library.cpp
- libopenfpga/libarchopenfpga/src/circuit_library.h
- libopenfpga/libarchopenfpga/src/read_xml_openfpga_arch.cpp
- openfpga_flow/openfpga_arch/k6_frac_N10_adder_chain_40nm_openfpga.xml
- openfpga_flow/openfpga_arch/k6_frac_N10_adder_chain_frac_mem32K_frac_dsp36_40nm_openfpga.xml
- openfpga_flow/openfpga_arch/k6_frac_N10_adder_chain_mem16K_40nm_openfpga.xml
- openfpga_flow/openfpga_arch/k6_frac_N10_adder_chain_mem16K_aib_40nm_openfpga.xml
- openfpga_flow/openfpga_arch/k6_frac_N10_adder_column_chain_40nm_openfpga.xml
- openfpga_flow/openfpga_arch/k6_frac_N10_adder_register_chain_40nm_openfpga.xml
- openfpga_flow/openfpga_arch/k6_frac_N10_adder_register_scan_chain_40nm_openfpga.xml
- openfpga_flow/openfpga_arch/k6_frac_N10_adder_register_scan_chain_depop50_40nm_openfpga.xml
- openfpga_flow/openfpga_arch/k6_frac_N10_adder_register_scan_chain_depop50_spypad_40nm_openfpga.xml
- Add check codes to help users debugging when default circuit models are not defined properly
- Add auto detection codes to identify unique and default circuit models
- Update documentation accordingly
Patch for issue #78
> [Architecture Languange] Patch the default circuit model definition

- .travis/fpga_verilog_reg_test.sh
- libopenfpga/libarchopenfpga/src/circuit_library.cpp
- openfpga_flow/openfpga_arch/k6_frac_N8_debuf_mux_40nm_openfpga.xml
- openfpga_flow/openfpga_arch/k6_frac_N8_inbuf_only_mux_40nm_openfpga.xml
- openfpga_flow/openfpga_arch/k6_frac_N8_outbuf_only_mux_40nm_openfpga.xml
- openfpga_flow/tasks/fpga_verilog/mux_design/debuf_mux/config/task.conf
- openfpga_flow/tasks/fpga_verilog/mux_design/inbuf_only_mux/config/task.conf
- openfpga_flow/tasks/fpga_verilog/mux_design/outbuf_only_mux/config/task.conf
Add 3 regression tests to validate the support on flexible routing multiplexer designs through Verilog-to-Verification flows
- Routing multiplexer without buffering
- Routing multiplexer with input buffer only
- Routing multiplexer with output buffer only
Also this PR contains a critical bug-fix for routing multiplexer with output buffer only
> Enriched regression test for flexible routing multiplexer designs

- openfpga_flow/misc/fpgaflow_default_tool_path.conf
- openfpga_flow/scripts/run_fpga_flow.py
Bug fixes to enable the following command
```
python3 ./openfpga_flow/scripts/run_fpga_flow.py ./openfpga_flow/vpr_arch/k4_frac_N4_40nm.xml ./openfpga_flow/benchmarks/micro_benchmark/and2/and2.v --top_module and2
```
> Edits to enable basic run_fpga_flow.py

- openfpga_flow/scripts/run_fpga_flow.py
Needed to enable 
```
python3 ./openfpga_flow/scripts/run_fpga_flow.py ./openfpga_flow/vpr_arch/k6_frac_N10_40nm.xml 
./openfpga_flow/benchmarks/pipelined_8bit_adder/pipelined_8bit_adder.v  --top_module pipelined_8bit_adder
```
> Fixed blif formatting bug

- docs/source/tutorials/compile.rst
Update docs with a note that shows how to enable VPR's GUI in the build sequence.
> Docs:  Updated note to enable VPR's GUI

- .travis/basic_reg_test.sh
- docs/source/manual/arch_lang/config_protocol.rst
- docs/source/manual/fpga_bitstream/fabric_dependent_bitstream.rst
- libopenfpga/libopenfpgautil/src/openfpga_decode.cpp
- libopenfpga/libopenfpgautil/src/openfpga_decode.h
- openfpga/src/fabric/build_top_module_memory.cpp
- openfpga/src/fpga_bitstream/build_device_bitstream.cpp
- openfpga/src/fpga_bitstream/build_fabric_bitstream.cpp
- openfpga/src/fpga_bitstream/fabric_bitstream.cpp
- openfpga/src/fpga_bitstream/fabric_bitstream.h
- openfpga/src/fpga_verilog/verilog_decoders.cpp
- openfpga/src/fpga_verilog/verilog_top_testbench.cpp
- openfpga/src/utils/fabric_bitstream_utils.cpp
- openfpga/src/utils/fabric_bitstream_utils.h
- openfpga_flow/openfpga_arch/k4_N4_40nm_multi_region_frame_openfpga.xml
- openfpga_flow/openfpga_arch/k4_N4_40nm_multi_region_frame_use_both_set_reset_openfpga.xml
- openfpga_flow/tasks/basic_tests/full_testbench/multi_region_configuration_frame/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/smart_fast_multi_region_configuration_frame/config/task.conf
Now frame-based configuration protocol supports multi-region as configuration chain and memory banks
In addition, fabric bitstream now supports don't care bit for frame-based addresses
> Multi-region support on Frame-based Configuration Protocol

- docs/source/manual/arch_lang/circuit_library.rst
- docs/source/manual/arch_lang/circuit_model_examples.rst
- libopenfpga/libarchopenfpga/src/check_circuit_library.cpp
- openfpga/src/fpga_bitstream/build_device_bitstream.cpp
- openfpga/src/fpga_verilog/verilog_api.cpp
- openfpga/src/fpga_verilog/verilog_preconfig_top_module.cpp
- openfpga/src/fpga_verilog/verilog_preconfig_top_module.h
- openfpga/src/utils/module_manager_utils.cpp
- openfpga_flow/openfpga_arch/k4_frac_N8_register_scan_chain_caravel_io_skywater130nm_fdhd_cc_openfpga.xml
- openfpga_flow/openfpga_arch/k6_frac_N8_stdcell_mux_40nm_openfpga.xml
- openfpga_flow/openfpga_cell_library/verilog/dff.v
Previously, all the configurable memory circuit models need two outputs, e.g., one for Q and the other for Qb, to generate fabric netlists and testbenches.
As standard cell FPGA does not require Qb to configure multiplexers, this may cause area overhead.
This pull request remove the restrictions.
> Remove the restrictions on requiring two outputs for configurable memory circuits

- openfpga/src/fabric/build_top_module.cpp
- openfpga/src/fabric/build_top_module_memory.cpp
- openfpga/src/fabric/build_top_module_memory.h
- openfpga/src/utils/openfpga_device_grid_utils.cpp
- Enhance error checking in fabric key parser: Only configurable blocks can be accepted as a key component
- Adapt the i/o numbering to the clockwise sequence which is more nature
> Multiple Bug Fixes

- openfpga_flow/OpenFPGAShellScripts/global_tile_clock_example_script.openfpga
- openfpga_flow/tasks/basic_tests/global_tile_ports/global_tile_clock/config/task.conf
- Fixed the bug on VPR routing failures due to the use of global clock from physical tile pins
- Enhance testing for the global clock port by adding sequential benchmarks
> Bug fix for global clock port using physical tile pins 

- vpr/src/device/check_rr_graph_obj.cpp
- vpr/src/device/rr_graph_obj.cpp
- vpr/src/route/rr_graph_reader.cpp
I've noticed that in the modified VPR version used by OpenFPGA segment ids are not set when a rr graph is loaded.
In this PR I've fixed that by creating segments in the `RRGraph` class and assigning them to nodes read from a rr graph XML file. I've also moved the essential check of the loaded rr graph after segment processing.
> Fix for rr graph loading by VPR

- .github/workflows/basic_reg_test.sh
- openfpga_flow/openfpga_arch/k4_frac_N8_reset_register_scan_chain_caravel_io_skywater130nm_fdhd_cc_openfpga.xml
- openfpga_flow/openfpga_cell_library/verilog/dff.v
- openfpga_flow/openfpga_cell_library/verilog/gpio.v
- openfpga_flow/tasks/basic_tests/global_tile_ports/global_tile_reset/config/task.conf
- openfpga_flow/vpr_arch/k4_frac_N8_tileable_reset_register_scan_chain_nonLR_caravel_io_skywater130nm.xml
-  Add a new test case `global_tile_reset` to validate that a global reset port can be defined through a port of a `physical_tile` in VPR architecture description.
- Add example architecture files that enable the test case
Add the following cells to the openfpga_cell_library that are required by the newly added architecture files
- Add a new scan-chain D-type flip-flop cell with reset signal
- Add a new I/O cell design with active-low signal to force the I/O in its input mode.
> Add a Test Case to CI which defines global reset port through tile port in VPR architecture

- docs/source/manual/arch_lang/annotate_vpr_arch.rst
- libopenfpga/libarchopenfpga/src/read_xml_tile_annotation.cpp
- openfpga_flow/openfpga_arch/k4_frac_N8_reset_register_scan_chain_caravel_io_skywater130nm_fdhd_cc_openfpga.xml
The XML syntax to define a default value for a global tile port was ``default_value="<int>"`` while in architecture example ``default_val="<int>"`` was used.
This has caused the default value definition in these examples to be dropped by parser.
This PR aims to fix this critical bug by setting the expected syntax as ``default_val="<int>"``, being consistent with circuit model port definition.
> Critical Bug fix in the XML Syntax when Defining Default Values for A Global Tile Port

- openfpga/src/annotation/annotate_simulation_setting.cpp
- openfpga/src/annotation/annotate_simulation_setting.h
- openfpga/src/base/openfpga_link_arch.cpp
- openfpga/src/fpga_verilog/verilog_formal_random_top_testbench.cpp
- openfpga/src/fpga_verilog/verilog_testbench_utils.cpp
- openfpga/src/fpga_verilog/verilog_testbench_utils.h
- openfpga/src/fpga_verilog/verilog_top_testbench.cpp
- openfpga/src/utils/simulation_utils.cpp
- openfpga/src/utils/simulation_utils.h
The reason behind is due to the self-testing testbenches update their error counters at the negative edges of operating clocks. As the counter is defined as registers in Verilog, its value is always released in the next negative edge. This caused that when there is only 1 simulation clock cycle to run, the error counter is never updated, resulting in false-positive problems.
Therefore, this PR forces the number of clock cycles in simulations to be at least 2, so that the error counter will be updated at least once.
> Force the number of simulation clock cycles to be >= 2 to avoid false-positive self-testing in testbenches

- docs/source/manual/arch_lang/circuit_model_examples.rst
- docs/source/manual/arch_lang/figures/native_frac_lut.svg
- docs/source/manual/arch_lang/figures/std_frac_lut.svg
- Correct the input port names for fracturable LUT schematic examples.
- Correct mode-select bits for dual-LUT2 modes
> Bug fix in LUT circuit model documentation

- .github/workflows/basic_reg_test.sh
- openfpga/src/base/openfpga_naming.cpp
- openfpga/src/base/openfpga_pb_pin_fixup.cpp
- openfpga/src/fabric/build_fabric_io_location_map.cpp
- openfpga/src/fabric/build_grid_module_duplicated_pins.cpp
- openfpga/src/fabric/build_grid_module_utils.cpp
- openfpga/src/fabric/build_grid_module_utils.h
- openfpga/src/fabric/build_grid_modules.cpp
- openfpga/src/fabric/build_top_module.cpp
- openfpga/src/fpga_bitstream/build_grid_bitstream.cpp
- openfpga/src/fpga_bitstream/build_routing_bitstream.cpp
- openfpga/src/fpga_sdc/analysis_sdc_grid_writer.cpp
- openfpga/src/fpga_verilog/verilog_grid.cpp
- openfpga_flow/tasks/basic_tests/tile_organization/tileable_io/config/task.conf
- openfpga_flow/vpr_arch/README.md
- openfpga_flow/vpr_arch/k4_N4_tileableIO_40nm.xml
- vpr/src/tileable_rr_graph/rr_graph_builder_utils.cpp
- vpr/src/tileable_rr_graph/tileable_rr_graph_node_builder.cpp
- Add a new example architecture where I/O tiles sit in the center part of FPGA grids.
- Relax I/O restrictions in FPGA tools to unlock this feature
Example grid layout (from VPR GUI):
> Support I/O tiles in the center part of FPGA grid layout

- openfpga/src/fpga_verilog/verilog_constants.h
- openfpga/src/fpga_verilog/verilog_mux.cpp
Currently, all the Verilog modules of routing multiplexers are outputted into an unique netlist.
This leads to a large Verilog netlists, which is hard to users to review and modify even using scripts.
This PR Split MUX Verilog netlist into two separated files: 
- one contains only primitive module, such as `mux_size12_basis_size4`, which are used to build large routing multiplexers, are placed in the same netlist. Users can freely modify this netlist to replace with custom cells.
- the other contains the top-level modules
> Organize Routing Multiplexer Verilog Netlist

- openfpga/src/base/openfpga_naming.cpp
- openfpga/src/base/openfpga_naming.h
- openfpga/src/fabric/build_mux_modules.cpp
- openfpga/src/fpga_spice/spice_constants.h
- openfpga/src/fpga_spice/spice_mux.cpp
- openfpga/src/fpga_verilog/verilog_mux.cpp
Currently, OpenFPGA create independent primitive modules when building routing multiplexer even in the same circuit model with different input size. This have causes a large number of primitive modules in different names while their RTL codes are the same. 
For example:
```
// ----- Verilog module for mux_2level_size12_basis_size4 -----
module mux_2level_size12_basis_size4(in,
mem,
mem_inv,
out);
//----- INPUT PORTS -----
input [0:3] in;
//----- INPUT PORTS -----
input [0:3] mem;
//----- INPUT PORTS -----
input [0:3] mem_inv;
//----- OUTPUT PORTS -----
output [0:0] out;
TGATE TGATE_0_ (
.in(in[0]),
.sel(mem[0]),
.selb(mem_inv[0]),
.out(out[0]));
TGATE TGATE_1_ (
.in(in[1]),
.sel(mem[1]),
.selb(mem_inv[1]),
.out(out[0]));
TGATE TGATE_2_ (
.in(in[2]),
.sel(mem[2]),
.selb(mem_inv[2]), …
```
> Netlist/Module size Reduction for Routing Multiplexers

- docs/requirements.txt
Documentation build is currently failing due to a new released major version of `sphnix bibitex` which is not incompatible. This PR aims to the solve the build errors by pinning `sphinxcontrib-bibtex` to a compatible version.
> Bug fix on the incompatible sphinx bibtex version

- .github/PULL_REQUEST_TEMPLATE.md
Previously the pull request template placed in `.github` directory is not considered by Github as a default template. 
This PR aims to fix the problem by placing the pull request template file in the right place as Github requests.
> Add default pull request template to the right position that Github requires

- docs/source/manual/arch_lang/annotate_vpr_arch.rst
- docs/source/manual/arch_lang/circuit_library.rst
- docs/source/manual/arch_lang/simulation_setting.rst
- libopenfpga/libarchopenfpga/src/read_xml_simulation_setting.cpp
- libopenfpga/libarchopenfpga/src/simulation_setting.cpp
- libopenfpga/libarchopenfpga/src/simulation_setting.h
- libopenfpga/libarchopenfpga/src/simulation_setting_fwd.h
- libopenfpga/libarchopenfpga/src/write_xml_simulation_setting.cpp
- libopenfpga/libarchopenfpga/src/write_xml_tile_annotation.cpp
- libopenfpga/libarchopenfpga/src/write_xml_utils.cpp
- libopenfpga/libarchopenfpga/src/write_xml_utils.h
- openfpga/src/annotation/annotate_simulation_setting.cpp
- openfpga/src/base/openfpga_sdc.cpp
- openfpga/src/fpga_sdc/analysis_sdc_writer.cpp
- openfpga/src/fpga_sdc/pnr_sdc_global_port.cpp
- openfpga/src/fpga_sdc/pnr_sdc_global_port.h
- openfpga/src/fpga_sdc/pnr_sdc_writer.cpp
- openfpga/src/fpga_sdc/pnr_sdc_writer.h
- openfpga/src/fpga_verilog/verilog_api.cpp
- openfpga/src/fpga_verilog/verilog_formal_random_top_testbench.cpp
- openfpga/src/fpga_verilog/verilog_testbench_utils.cpp
- openfpga/src/fpga_verilog/verilog_top_testbench.cpp
- openfpga_flow/openfpga_simulation_settings/fixed_4clock_sim_openfpga.xml
- openfpga_flow/tasks/basic_tests/global_tile_ports/global_tile_4clock/config/task.conf
OpenFPGA only accepts a single operating clock frequency to be considered in the testbench and SDC generators.
This has become a critical barrier when implementing multi-clock FPGA fabrics and verification.
This PR introduces new XML syntax to the simulation setting description.
Now users are allowed to define multiple clock names and frequency.
The clock names should be validated to match a clock port in the FPGA fabric.
The clock frequencies are used in the generating testbenches and timing constraints in SDC format.
> Support Multiple Clock Definition in Testbench and SDC Generators

- libopenfpga/libopenfpgautil/CMakeLists.txt
- libopenfpga/libopenfpgautil/cmake/modules/configure_version.cmake
- libopenfpga/libopenfpgautil/src/openfpga_version.cpp.in
- libopenfpga/libopenfpgautil/src/openfpga_version.h
- openfpga/src/base/openfpga_title.cpp
To address issue #180 
This PR added version display when launching the binary of OpenFPGA.
For example, when executing `openfpga -i`, the shell interface will display:
```
Start interactive mode of OpenFPGA...
___                   _____ ____   ____    _     
/ _ \ _ __   ___ _ __ |  ___|  _ \ / ___|  / \    
| | | | '_ \ / _ \ '_ \| |_  | |_) | |  _  / _ \   
| |_| | |_) |  __/ | | |  _| |  __/| |_| |/ ___ \  
\___/| .__/ \___|_| |_|_|   |_|    \____/_/   \_\ 
|_|                                          
OpenFPGA: An Open-source FPGA IP Generator
Versatile Place and Route (VPR)
FPGA-Verilog
FPGA-SPICE
FPGA-SDC
FPGA-Bitstream
This is a free software under the MIT License
Copyright (c) 2018 …
```
> Add OpenFPGA version display

- openfpga/src/fpga_verilog/verilog_testbench_utils.cpp
To address issue #178 
This PR patched testbench generator of FPGA-Verilog by removing the signal initialization for unused general-purpose output ports of FPGA fabrics.
Attached an example testbench outputted by OpenFPGA after this patch.
You can see all the signal assignment for `SOC_OUT` is now removed from generator (as shown in #178)
[and2_autocheck_top_tb.zip](https://github.com/lnis-uofu/OpenFPGA/files/5859203/and2_autocheck_top_tb.zip)
> Avoid to output initial signal for general-purpose output ports of FPGA fabrics in Verilog testbenches

- docs/source/manual/openfpga_shell/launch_openfpga_shell.rst
- libopenfpga/libopenfpgashell/src/shell.h
- libopenfpga/libopenfpgashell/src/shell.tpp
- openfpga/src/main.cpp
- To address issue #183 
Now openfpga shell has a new option ``--batch_execution`` or in short as ``-batch``
which allows batch execution of openfpga commands.
When enabled, OpenFPGA will abort immediately when fatal errors occurred.
Otherwise, OpenFPGA will enter interactive mode when fatal errors occurred.
Documentation has been updated for the new option.
Also, this PR enhanced the return code of OpenFPGA shell.
If aborted, OpenFPGA will return error code (1) as fatal errors occurred.
> Support batch mode when executing OpenFPGA commands

- .github/workflows/build.yml
The Docker image uploaded from master creates alternate tag with short SHA 
`openfpga-master:latest` - points to latest commit on master 
`openfpga-master:xxxxxxxx` - points to specific commit on master
> [CICD] Added SHA tag to docker build image

- README.md
- docs/source/tutorials/compile.rst
---
Changed link to dependencies for compilation in the docs
---
https://github.com/lnis-uofu/OpenFPGA/issues/211
- Current link (https://github.com/LNIS-Projects/OpenFPGA/blob/0cfb88a49f152aab0a06f309ff160f222bb51ed7/.travis.yml#L34) points to travis.yml which is out of date.
- Pull request changes the link to point to the correct file
> Changed readthedocs.io dependencies link

- README.md
- docs/requirements.txt
- docs/source/conf.py
- docs/source/overview/motivation.rst
- docs/source/tutorials/compile.rst
- docs/source/tutorials/design_flow/generate_fabric.rst
- docs/source/tutorials/design_flow/index.rst
- docs/source/tutorials/design_flow/verilog2verification.rst
Current OpenFPGA miss tutorial videos.
This PR added to README.md about the youtube links to the tutorial video.
This PR also added embedded video to online documentation.
This is how it looks like.
In addition, a new tutorial `generate_fabric` was added along with an embedded video.
> Add tutorial videos to Documentation

- docs/requirements.txt
- docs/source/conf.py
- docs/source/overview/motivation.rst
- docs/source/tutorials/compile.rst
- docs/source/tutorials/design_flow/generate_fabric.rst
Readthedocs reports build errors when converting html to pdf.
See details at the [link](https://readthedocs.org/projects/openfpga/builds/)
- Skip youtube video when building pdf so that PDF generation will have no errors
-  Apply SVG2PDF converter so that svg images can be included in the pdf
> Documentation Patches on Supporting PDF builds

- .readthedocs.yml
- docs/requirements.txt
- docs/source/conf.py
- docs/source/manual/arch_lang/circuit_model_examples.rst
- Sphinx builder skip SVG when outputting latex
- 
- Add package 'imgconverter' to convert the SVG to PNG, when building the latex files.
> Support SVG in Sphinx Latex building

- openfpga_flow/scripts/run_fpga_flow.py
- What is currently done? (Provide issue link if applicable) ACE for every run of yosys_vpr flow 
- What does this pull request change?  This pull request makes ACE2 run optional (it only executes when Power estimation flag is made true)
> [Flow] ACE is optional during flow script, only runs when power estimation is on 

- .github/workflows/build.yml
- .github/workflows/quicklogic_reg_test.sh
Currently, Quicklogic's regression tests are part of the basic tests.
As quicklogic's test is going to grow with more benchmark suites to be imported, it is proper to create a dedicated regression test run.
This PR move the current test cases for QuickLogic to a dedicated CI run, in parallel to basic_tests, fpga_verilog_tests, *etc.*
> Move quicklogic regresssion tests to a dedicated CI run

- .github/workflows/build.yml
The docker image has OPENFPGA_PATH already setup to the already installed binary, during current regression test it uses that path to run regression script. This commit unset the OPENFPGA_PATH so that new PATH can be setup.
> [Bugfix] Docker regression using master regression scripts

- openfpga_flow/openfpga_shell_scripts/quicklogic_flow_example_script.openfpga
---
---
Removing verilog testbench generation as lot of disk space is required and test bench generation is anyways not required as these tests are not running simulation.
> Disabling verilog testbench generation for quicklogic tests

- docs/source/manual/arch_lang/config_protocol.rst
- openfpga/src/fabric/build_top_module.cpp
To address issue #240 
Instead of a warning message, now OpenFPGA will abort and throw a fatal error message when the number of configurable region is different between fabric key and architecture definition
> Throw fatal error when the number of configurable region is different between fabric key and architecture definition

- docs/source/manual/arch_lang/annotate_vpr_arch.rst
- docs/source/manual/file_formats/bitstream_setting.rst
- libopenfpga/libarchopenfpga/src/bitstream_setting.cpp
- libopenfpga/libarchopenfpga/src/bitstream_setting.h
- libopenfpga/libarchopenfpga/src/read_xml_bitstream_setting.cpp
- libopenfpga/libarchopenfpga/src/write_xml_bitstream_setting.cpp
- openfpga/src/annotation/annotate_bitstream_setting.cpp
- openfpga/src/annotation/vpr_bitstream_annotation.cpp
- openfpga/src/annotation/vpr_bitstream_annotation.h
- openfpga/src/fpga_bitstream/build_grid_bitstream.cpp
- openfpga/src/repack/physical_pb.cpp
- openfpga/src/repack/physical_pb.h
- openfpga/src/utils/physical_pb_utils.cpp
- openfpga_flow/misc/qlf_yosys.ys
- openfpga_flow/misc/ys_tmpl_rewrite_flow.ys
- openfpga_flow/misc/ys_tmpl_yosys_vpr_flow_with_rewrite.ys
- openfpga_flow/openfpga_arch/k4_frac_N8_reset_softadderSuperLUT_register_scan_chain_caravel_io_skywater130nm_fdhd_cc_openfpga.xml
- openfpga_flow/openfpga_cell_library/verilog/frac_lut4_arith.v
- openfpga_flow/scripts/run_fpga_flow.py
- openfpga_flow/scripts/run_fpga_task.py
- openfpga_flow/tasks/quicklogic_tests/lut_adder_test/config/bitstream_annotation.xml
- openfpga_flow/tasks/quicklogic_tests/lut_adder_test/config/task.conf
---
Name: Extended Yosys support in OpenFPGA tasks
About: Running yosys in OpenFPGA flow
---
Following changes has been introduced
1. The script parameters defined in task file are available in the YOSYS template script as a template variables 
-  Any variable defined under `[SCRIPT_PARAM_XXXXX]` will be available in the Yosys template 
- For example
- `[SCRIPT_PARAM_XXXXX]\n YOSYS_ARGS=-param -param` can be referred in the template as  `${YOSYS_ARGS}`
2. Yosys rewrite Verilog, template support
- Similar to yosys synthesis template `<benchmakeName>_yosys`
- Now OpenFPGA task supports specifying the `<benchmakeName>_yosys_rewrite` variable under `[SYNTHESIS_PARAM]` section, which specify the template file should be use for rewriting the Verilog for a specific benchmark during OpenFPGA task …
> [Task/Flow] Extended Yosys support in OpenFPGA task

- docs/source/manual/file_formats/fabric_bitstream.rst
- openfpga/src/fpga_bitstream/write_text_fabric_bitstream.cpp
- openfpga/src/fpga_bitstream/write_xml_fabric_bitstream.cpp
- openfpga/src/fpga_verilog/verilog_top_testbench.cpp
- openfpga/src/utils/fabric_bitstream_utils.cpp
- openfpga/src/utils/fabric_bitstream_utils.h
To address issue #268 
Previously, OpenFPGA's fabric bitstream file formats only supports single configuration region.
This PR improves the fabric bitstream writers to output bitstream files supporting multiple configuration regions.
> Fabric bitstream writer supports multiple regions

- libopenfpga/libpcf/src/pin_constraints.cpp
- libopenfpga/libpcf/src/pin_constraints.h
- openfpga/src/fpga_verilog/verilog_preconfig_top_module.cpp
- openfpga/src/fpga_verilog/verilog_top_testbench.cpp
- openfpga_flow/openfpga_shell_scripts/example_without_ace_script.openfpga
- openfpga_flow/tasks/basic_tests/k4_series/k4n4_fracff/config/pin_constraints.xml
- openfpga_flow/tasks/basic_tests/k4_series/k4n4_fracff/config/task.conf
Previously, the pin constraints are only applied to clock ports, as part of the multi-clock support.
This results in a limitation on pin assignments for non-clock global ports, especially the ``reset`` ports.
``reset`` nets are typically wired to a dedicated pin of FPGA fabric, which is not a regular data I/O.
Therefore, pin constraints are required to assign ``reset`` nets to proper pins.
This PR improves the following aspects:
> Verilog testbench generator now accepts pin constraints on non-clock global ports

- libopenfpga/libpcf/src/pin_constraints.cpp
- libopenfpga/libpcf/src/pin_constraints.h
- openfpga/src/fpga_verilog/verilog_api.cpp
- openfpga/src/fpga_verilog/verilog_formal_random_top_testbench.cpp
- openfpga/src/fpga_verilog/verilog_formal_random_top_testbench.h
- openfpga/src/fpga_verilog/verilog_preconfig_top_module.cpp
- openfpga/src/fpga_verilog/verilog_testbench_utils.cpp
- openfpga/src/fpga_verilog/verilog_testbench_utils.h
- openfpga/src/fpga_verilog/verilog_top_testbench.cpp
- openfpga/src/utils/fabric_global_port_info_utils.cpp
- openfpga/src/utils/fabric_global_port_info_utils.h
Currently, OpenFPGA assign random waveforms to drive reset pins of users' HDL designs in both full testbench and preconfigured testbench.
This has causes verification to be low coverage for those benchmarks with reset signals. 
This PR improves the testbench generator to
> Enable correct reset stimuli in testbench generators

- docs/source/manual/file_formats/repack_design_constraints.rst
- libopenfpga/librepackdc/src/repack_design_constraints.cpp
- libopenfpga/librepackdc/src/repack_design_constraints.h
- openfpga/src/repack/repack.cpp
- openfpga_flow/benchmarks/micro_benchmark/and2_latch_2clock/and2_latch_2clock.v
- openfpga_flow/tasks/basic_tests/global_tile_ports/global_tile_4clock/config/task.conf
Previously, OpenFPGA's repacker has a bug which can skip the routing for clock nets which are constrained by the repack design constraint file. This has caused incorrect bitstreams and captured in latest verification effort.
This PR does the following improvement: 
> Patches on multi-clock support in repacking stage

- openfpga_flow/openfpga_shell_scripts/vtr_benchmark_example_script.openfpga
Currently, the openfpga shell script for VTR benchmarks does not route constant nets, which are very popular in the modern benchmarks.
This PR enables constant net routing for VTR benchmarks.
> Enable constant net routing for VTR benchmarks

- openfpga_flow/regression_test_scripts/fpga_verilog_reg_test.sh
- openfpga_flow/tasks/fpga_verilog/dsp/wide_multi_mode_mult_16x16/config/task.conf
- openfpga_flow/vpr_arch/k4_frac_N8_tileable_reset_softadder_register_scan_chain_wide_frac_dsp16_nonLR_caravel_io_skywater130nm.xml
> 
> 
> Currently, OpenFPGA has the following limitations:
> - [x] DSP block has a width=1 while height > 1
> This has not covered some typical cases where heterogeneous blocks have width > 1
>
> 
> 
> This PR improves in the following aspects:
> - [x] Added a new architecture where a fracturable 16-bit DSP block has a width of 2 and a height of 2
> - [x] Added a test for the new architecture using 8/16-bit MAC benchmarks
> Screen shot …
> Test addition for FPGA architecture with multi-width DSP blocks

- openfpga_flow/benchmarks/micro_benchmark/blinking/blinking.v
- openfpga_flow/tasks/basic_tests/full_testbench/fast_configuration_chain/config/task.conf
> 
> 
>  Benchmark suites are never enough for OpenFPGA.
> 
> 
>
> 
> 
> This PR improves in the following aspects: 
>  - [ ] Add a 1-bit blinking to the micro benchmark suite
>  - [ ] Use the blinking benchmark in tests
> 
> - [ ] VPR
> - [ ] …
> Introduce Micro benchmark: 1-bit Blinking 

- docs/source/manual/file_formats/bitstream_distribution_file.rst
- docs/source/manual/file_formats/index.rst
- docs/source/manual/openfpga_shell/openfpga_commands/fpga_bitstream_commands.rst
- libopenfpga/libfpgabitstream/src/bitstream_manager_utils.cpp
- libopenfpga/libfpgabitstream/src/bitstream_manager_utils.h
- libopenfpga/libfpgabitstream/src/report_arch_bitstream_distribution.cpp
- libopenfpga/libfpgabitstream/src/report_arch_bitstream_distribution.h
- libopenfpga/libfpgabitstream/test/test_arch_bitstream.cpp
- openfpga/src/base/openfpga_bitstream.cpp
- openfpga/src/base/openfpga_bitstream.h
- openfpga/src/base/openfpga_bitstream_command.cpp
- openfpga_flow/openfpga_shell_scripts/report_bitstream_distribution_example_script.openfpga
- openfpga_flow/regression_test_scripts/fpga_bitstream_reg_test.sh
- openfpga_flow/tasks/fpga_bitstream/report_bitstream_distribution/custom_depth/config/task.conf
- openfpga_flow/tasks/fpga_bitstream/report_bitstream_distribution/default_depth/config/task.conf
> 
> 
> Currently, OpenFPGA has the following limitations: 
>  - [X] Users have very limited scope on how the bitstream is distributed between modules, e.g., CB/SB/CLBs. The bitstream database is very bulky and hard for users to inspect.
>
> 
> 
>  This PR improves in the following aspects:
>  - [X] Added a new command 'report_bitstream_distribution' which can report number of configuration bits per block to an XML file
>  - [X] Added …
> Report bitstream distribution

- openfpga/src/fpga_sdc/pnr_sdc_global_port.cpp
- openfpga/src/fpga_sdc/pnr_sdc_global_port.h
- openfpga/src/fpga_sdc/pnr_sdc_writer.cpp
…straints
> 
> 
> 
> 
> 
Address issue #316 
>
> 
> 
> This PR improves in the following aspects:
>  - [X] Add time unit support to SDC writer on the timing constraints for global port
> 
> - [ ] VPR
> - [X] FPGA-SDC
> - [ ] …
> Patch FPGA-SDC to consider time unit in global port timing constraints

- docs/source/manual/openfpga_shell/openfpga_commands/fpga_bitstream_commands.rst
- docs/source/manual/openfpga_shell/openfpga_commands/fpga_verilog_commands.rst
- openfpga/src/base/openfpga_bitstream.cpp
- openfpga/src/base/openfpga_bitstream_command.cpp
- openfpga/src/base/openfpga_verilog.cpp
- openfpga/src/base/openfpga_verilog_command.cpp
- openfpga/src/fpga_bitstream/fast_configuration.cpp
- openfpga/src/fpga_bitstream/fast_configuration.h
- openfpga/src/fpga_bitstream/write_text_fabric_bitstream.cpp
- openfpga/src/fpga_bitstream/write_text_fabric_bitstream.h
- openfpga/src/fpga_verilog/verilog_formal_random_top_testbench.cpp
- openfpga/src/fpga_verilog/verilog_testbench_utils.cpp
- openfpga/src/fpga_verilog/verilog_testbench_utils.h
- openfpga/src/fpga_verilog/verilog_top_testbench.cpp
- openfpga_flow/openfpga_shell_scripts/write_full_testbench_example_script.openfpga
- openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain_config_enable_scff/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain_use_reset/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain_use_resetb/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain_use_set/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain_use_set_reset/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain_use_setb/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/fast_configuration_chain/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/fast_configuration_chain_use_set/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/multi_region_configuration_chain/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/smart_fast_configuration_chain/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/smart_fast_multi_region_configuration_chain/config/task.conf
Address issue #319 
This is a follow-up pull request mention in #320 
> 
> 
> 
> 
> 
>
> 
> 
An example of bitstream file (*.bit):
```
// Fabric bitstream
// Version: 1.0.0-dev+27fa1560-dirty
// Date: Fri Jun  4 19:48:11 2021
// Bitstream length: 571
// Bitstream width (LSB -> MSB): 4
0000
0000
0000
0000
```
> 
> - [ ] VPR
> - [ ] Tileable …
> Support fast configuration in bitstream writer and full testbench that reads external bitstream file

- docs/source/manual/file_formats/fabric_bitstream.rst
- openfpga/src/fpga_bitstream/write_text_fabric_bitstream.cpp
- openfpga/src/fpga_verilog/verilog_top_testbench.cpp
- openfpga_flow/tasks/basic_tests/full_testbench/configuration_frame/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/configuration_frame_ccff/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/configuration_frame_scff/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/configuration_frame_use_reset/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/configuration_frame_use_resetb/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/configuration_frame_use_set/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/configuration_frame_use_set_reset/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/configuration_frame_use_setb/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/fast_configuration_frame/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/fast_configuration_frame_use_set/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/multi_region_configuration_frame/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/smart_fast_configuration_frame/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/smart_fast_multi_region_configuration_frame/config/task.conf
Address issue #319
This is a follow-up pull request mention in #321
> 
> 
> 
> 
> 
>
> 
> 
> 
> - [ ] VPR
> - [ ] …
> Support frame-based configuration protocol in bitstream writer and full testbench that reads external bitstream file

- docs/source/manual/file_formats/fabric_bitstream.rst
- openfpga/src/fpga_bitstream/write_text_fabric_bitstream.cpp
- openfpga/src/fpga_verilog/verilog_top_testbench.cpp
- openfpga_flow/tasks/basic_tests/full_testbench/fast_memory_bank/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/fast_memory_bank_use_set/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/memory_bank/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/memory_bank_use_reset/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/memory_bank_use_resetb/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/memory_bank_use_set/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/memory_bank_use_set_reset/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/memory_bank_use_setb/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/multi_region_memory_bank/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/smart_fast_memory_bank/config/task.conf
- openfpga_flow/tasks/basic_tests/full_testbench/smart_fast_multi_region_memory_bank/config/task.conf
- Address issue #319
- This is a follow-up pull request mention in #323
> 
> 
> 
> 
> 
>
> 
> 
> 
> - [ ] VPR
> - [ ] …
> Support memory bank configuration protocol in bitstream writer and full testbench that reads external bitstream file

- openfpga/src/fpga_bitstream/write_text_fabric_bitstream.cpp
- openfpga/src/fpga_verilog/verilog_top_testbench.cpp
- openfpga_flow/tasks/basic_tests/full_testbench/flatten_memory/config/task.conf
- Address issue #319
- This is a follow-up pull request mention in #324
> 
> 
> 
> 
> 
>
> 
> 
> 
> - [ ] VPR
> - [X] FPGA-Verilog
> - [X] FPGA-Bitstream
> - [ ] …
> Support flatten configuration protocol in bitstream writer and full testbench that reads external bitstream file

- docs/source/manual/openfpga_shell/openfpga_commands/fpga_verilog_commands.rst
- openfpga/src/base/openfpga_verilog.cpp
- openfpga/src/base/openfpga_verilog_command.cpp
- openfpga/src/fpga_verilog/verilog_api.cpp
- openfpga/src/fpga_verilog/verilog_formal_random_top_testbench.cpp
- openfpga/src/fpga_verilog/verilog_formal_random_top_testbench.h
- openfpga/src/fpga_verilog/verilog_preconfig_top_module.cpp
- openfpga/src/fpga_verilog/verilog_preconfig_top_module.h
- openfpga/src/fpga_verilog/verilog_testbench_options.cpp
- openfpga/src/fpga_verilog/verilog_testbench_options.h
- openfpga/src/fpga_verilog/verilog_top_testbench.cpp
- openfpga_flow/openfpga_shell_scripts/behavioral_verilog_example_script.openfpga
- openfpga_flow/openfpga_shell_scripts/implicit_verilog_example_script.openfpga
- openfpga_flow/openfpga_shell_scripts/verilog_default_net_type_example_script.openfpga
> 
> 
-  Verilog testbench generators do **not** support ``default_net_type`` customization. The net type is always set to ``none``. For example,
```
`default_nettype none
module and2_autocheck_top_tb;
```
This has caused some compatibility issues in some HDL simulators, e.g., Modelsim.
>
> 
>  …
> Support ``default_net_type`` customization in Verilog testbench generator

- openfpga_flow/scripts/run_fpga_task.py
> - [x] To address an existing issue. If so, please provide a link to the issue: <issue id>
> 
> 
> 
> 
> 
Address issue #330 
Previous python script is buggy when outputting error message when task directory is not found
>
> 
> 
> 
> 
> 
Patched the script. Here is how the error message look like now.
```
[u6018939@lnissrv4 OpenFPGA]$ python3 openfpga_flow/scripts/run_fpga_task.py aaa
INFO (     MainThread) - Set up to run 2 Parallel threads
INFO (     MainThread) - Currently running task aaa
ERROR (     MainThread) - Task …
```
> Openfpga flow script outputs detailed error message when task directory is not found

- openfpga_flow/scripts/run_fpga_task.py
> 
> 
This has been a strong limitation because we should not constrain users when naming their top modules of HDL designs.
>
> 
> 
Here is an example:
- When define a benchmark top module name:
```
bench0_top = and2
```
- The flow-run script now creates a local run directory:
```
openfpga_flow/tasks/fpga_bitstream/write_io_mapping/run001/k6_fra …
```
> Support benchmarks with same top module names in openfpga flow script

- libopenfpga/libopenfpgautil/src/openfpga_reserved_words.h
- openfpga/src/base/openfpga_bitstream.cpp
- openfpga/src/fabric/build_top_module_connection.cpp
- openfpga/src/fpga_bitstream/build_io_mapping_info.cpp
- openfpga/src/fpga_bitstream/build_io_mapping_info.h
- openfpga/src/fpga_verilog/verilog_formal_random_top_testbench.cpp
- openfpga/src/fpga_verilog/verilog_testbench_utils.h
> - [x] To address an existing issue. If so, please provide a link to the issue: <issue id>
> 
> 
> 
> 
> 
Address issue #308 
>
> 
> 
Example of io_mapping.xml outputted:
```
<io_mapping>
<io name="gfpga_pad_GPIO_PAD[6:6]" net="a" dir="input"/>
<io name="gfpga_pad_GPIO_PAD[1:1]" net="b" dir="input"/>
<io name="gfpga_pad_GPIO_PAD[9:9]" net="c" dir="output"/>
</io_mapping>
```
> 
> - [ ] VPR
> - [ ] Tileable routing architecture …
> Write io mapping

- docs/source/manual/openfpga_shell/openfpga_commands/fpga_verilog_commands.rst
- openfpga/src/base/openfpga_verilog.cpp
- openfpga/src/base/openfpga_verilog_command.cpp
- openfpga/src/fpga_verilog/verilog_api.cpp
- openfpga/src/fpga_verilog/verilog_simulation_info_writer.cpp
- openfpga/src/fpga_verilog/verilog_simulation_info_writer.h
- openfpga/src/fpga_verilog/verilog_testbench_options.cpp
- openfpga/src/fpga_verilog/verilog_testbench_options.h
> 
> 
>
> 
> 
> 
> - [ ] VPR
> - [ ] Regression …
> Update Simulation Exchangeable Information Writer

- openfpga/src/fpga_verilog/verilog_preconfig_top_module.cpp
- openfpga_flow/openfpga_shell_scripts/preconfig_fabric_example_script.openfpga
- openfpga_flow/regression_test_scripts/fpga_verilog_reg_test.sh
- openfpga_flow/tasks/fpga_verilog/verilog_netlist_formats/embed_bitstream_modelsim/config/task.conf
- openfpga_flow/tasks/fpga_verilog/verilog_netlist_formats/embed_bitstream_none/config/task.conf
> 
> 
>
> 
> 
> 
> - [ ] VPR
> - [x] …
> Bug fix in Preconfigured Fabric Wrapper Generator

- openfpga/src/fpga_verilog/verilog_formal_random_top_testbench.cpp
- openfpga/src/fpga_verilog/verilog_simulation_info_writer.cpp
- openfpga/src/utils/simulation_utils.cpp
- openfpga/src/utils/simulation_utils.h
> 
> 
This caused the simulation time to be inconsistent with what user expect or defined in simulation setting.
There should be no hidden parameters impacting simulation time
>
> 
> 
> 
> - [ ] VPR …
> Remove the hardcoded factor when computing simulation timing

- openfpga/src/fpga_verilog/verilog_preconfig_top_module.cpp
- openfpga_flow/openfpga_cell_library/verilog/dff.v
> - [X] To address an existing issue. If so, please provide a link to the issue: #346 
To address issue #346 
> 
> 
> 
> 
> 
>
> 
> 
> 
> - [ ] VPR
> - [X] FPGA-Verilog
> - [X] Cell library
> - [ ] …
> Use ``force`` in preconfigured testbenches to avoid instrusive code modification on flip-flop HDL

- openfpga/src/fpga_verilog/verilog_formal_random_top_testbench.cpp
> 
> 
> 
> 
> 
To address issue #351 
>
> 
> 
> 
> 
> 
There was a bug in the testbench generator on the reset stimuli:
```
initial begin
@negedge (clock)
assign reset = ~reset;
end
```  
This violates the Verilog syntax and caused Modelsim to error out.
However, it is weird that iVerilog does not flag
Now it changes to 
```
initial begin
@negedge (clock)
reset <= ~reset;
end
```  
> 
> …
>  Bug fix on the reset stimuli generator

- openfpga_flow/scripts/run_fpga_task.py
Allows benchmark specific variable declaration in the task file
```
[SYNTHESIS_PARAM]
bench0_top = and2
bench0_pin_conf_file = ${TASK_DIR}
```
Makes `PIN_CONF_FILE` variable during openfpgashell run of specific benchmark
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR
> - [ ] Continous …
> [Flow] Allows benchmark specific Variable declaration

- docs/source/manual/file_formats/pin_constraints_file.rst
- libopenfpga/libpcf/src/pin_constraints.cpp
- libopenfpga/libpcf/src/pin_constraints.h
- libopenfpga/libpcf/src/read_xml_pin_constraints.cpp
- libopenfpga/libpcf/src/write_xml_pin_constraints.cpp
- openfpga/src/fpga_verilog/verilog_formal_random_top_testbench.cpp
- openfpga/src/fpga_verilog/verilog_top_testbench.cpp
> 
> 
> 
> 
> 
Address issue #350 
>
> 
> 
> 
> - [ ] VPR
> - [X] OpenFPGA libraries
> - [X] FPGA-Verilog
> - [ ] …
> [WIP] Support custom default value in Pin Constraint File

- openfpga_flow/scripts/run_fpga_task.py
> ### Motivation of the pull request
> - [X] To address an existing issue. If so, please provide a link to the issue: #365 
> 
> 
> 
> 
Cannot run tasks which are specified by an absolute filesystem path.
> 
>
> 
> 
> 
> 
This PR adds an absolute path check for the given project directory.
> 
> 
> - [ ] VPR
> - [X] Flow scripts
> …
> Accept absolute project paths in the 'run_fpga_task.py' script

- .gitmodules
- openfpga/src/fpga_verilog/verilog_formal_random_top_testbench.cpp
- openfpga_flow/misc/ys_tmpl_yosys_vpr_bram_dsp_dff_flow.ys
- openfpga_flow/misc/ys_tmpl_yosys_vpr_bram_dsp_flow.ys
- openfpga_flow/misc/ys_tmpl_yosys_vpr_bram_flow.ys
- openfpga_flow/misc/ys_tmpl_yosys_vpr_dff_flow.ys
- openfpga_flow/misc/ys_tmpl_yosys_vpr_dsp_flow.ys
- openfpga_flow/misc/ys_tmpl_yosys_vpr_flow.ys
- openfpga_flow/misc/ys_tmpl_yosys_vpr_flow_with_rewrite.ys
- openfpga_flow/openfpga_cell_library/verilog/dff.v
- openfpga_flow/openfpga_shell_scripts/generate_bitstream_fix_device_example_script.openfpga
- openfpga_flow/openfpga_shell_scripts/implicit_verilog_example_script.openfpga
- openfpga_flow/regression_test_scripts/quicklogic_reg_test.sh
- openfpga_flow/tasks/benchmark_sweep/counter/config/task.conf
- openfpga_flow/tasks/benchmark_sweep/signal_gen/config/task.conf
- openfpga_flow/tasks/benchmark_sweep/vtr_benchmarks/config/vtr_benchmark_golden_results.csv
- openfpga_flow/tasks/fpga_bitstream/generate_bitstream/device_48x48/config/task.conf
- openfpga_flow/tasks/fpga_bitstream/generate_bitstream/device_96x96/config/task.conf
- openfpga_flow/tasks/fpga_bitstream/repack_wire_lut/config/task.conf
- openfpga_flow/tasks/fpga_verilog/verilog_netlist_formats/implicit_verilog/config/task.conf
- openfpga_flow/tasks/fpga_verilog/verilog_netlist_formats/implicit_verilog_default_nettype_wire/config/task.conf
- openfpga_flow/vpr_arch/k4_frac_N4_tileable_fracff_40nm.xml
- openfpga_flow/vpr_arch/k6_frac_N10_tileable_adder_chain_dpram8K_dsp36_fracff_40nm.xml
> - [x] To address an existing issue. If so, please provide a link to the issue: #371 
> 
> 
- Current Yosys submodule is a QuickLogic version. As agreed in #371 , we should go for the yosys HQ version where we have most developers and updates
> 
>
> 
> 
> 
> 
> - [ ] VPR
> - [ ] …
> Use Yosys HQ v0.10 as a submodule

- openfpga_flow/regression_test_scripts/quicklogic_reg_test.sh
- openfpga_flow/tasks/quicklogic_tests/counter_5clock_test/config/task.conf
Re-Enable remaining advanced quiicklogic regression tests: counter_5clock,sdc_controller, lut_adder tests
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR
> - [ ] …
> re-enable counter_5clock,sdc_controller, lut_adder tests

- .github/workflows/build.yml
> - [x] To address an existing issue. If so, please provide a link to the issue: #398 
> 
> 
- CI will run on all the pushes in a PR. This will jam CI runners (CI runs on out-of-date commits in a PR)
> 
> 
>
> 
> 
> 
> 
> - [ ] VPR …
> Now CI tests will cancel previous runs

- openfpga_flow/benchmarks/micro_benchmark/mult/mult_2_pipelined/mult_2_pipelined.v
- openfpga_flow/openfpga_arch/README.md
- openfpga_flow/openfpga_arch/k4_N4_40nm_dsp8reg_cc_openfpga.xml
- openfpga_flow/regression_test_scripts/fpga_verilog_reg_test.sh
- openfpga_flow/tasks/fpga_verilog/dsp/single_mode_mult_8x8_reg/config/task.conf
- openfpga_flow/vpr_arch/README.md
- openfpga_flow/vpr_arch/k4_N4_tileable_dsp8reg_40nm.xml
> 
> 
- DSP blocks are too simple, which only contain multipliers.
- Modern DSP blocks contain input and output registers to properly pipeline datapath.
>
> 
> 
> 
> - [ ] VPR …
> New test case: DSP block with input and output registers

- libopenfpga/libfpgabitstream/src/report_arch_bitstream_distribution.cpp
- openfpga/src/fpga_bitstream/write_text_fabric_bitstream.cpp
- openfpga/src/fpga_bitstream/write_xml_io_mapping.cpp
- openfpga_flow/regression_test_scripts/basic_reg_test.sh
- openfpga_flow/tasks/basic_tests/no_time_stamp/golden_outputs_no_time_stamp/bitstream_distribution.xml
- openfpga_flow/tasks/basic_tests/no_time_stamp/golden_outputs_no_time_stamp/fabric_bitstream.bit
- openfpga_flow/tasks/basic_tests/no_time_stamp/golden_outputs_no_time_stamp/pin_mapping.xml
> - [x] To address an existing issue. If so, please provide a link to the issue: #499 
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
This is a follow-up PR to fix the errors in basic regression tests due to ``--no_time_stamp`` support
> 
> - [ ] VPR
> - [ ] …
> Patch the errors in basic regression tests due to ``--no_time_stamp`` support

- docs/source/manual/openfpga_shell/openfpga_commands/fpga_verilog_commands.rst
- openfpga/src/base/openfpga_verilog.cpp
- openfpga/src/base/openfpga_verilog_command.cpp
- openfpga/src/fpga_verilog/verilog_auxiliary_netlists.cpp
- openfpga/src/fpga_verilog/verilog_auxiliary_netlists.h
- openfpga/src/fpga_verilog/verilog_testbench_options.cpp
- openfpga/src/fpga_verilog/verilog_testbench_options.h
- openfpga_flow/openfpga_shell_scripts/preconfigured_testbench_relative_path_example_script.openfpga
- openfpga_flow/regression_test_scripts/fpga_verilog_reg_test.sh
- openfpga_flow/scripts/run_fpga_flow.py
- openfpga_flow/tasks/fpga_verilog/verilog_netlist_formats/preconfig_testbench_use_relative_path/config/task.conf
> - [x] To address an existing issue. If so, please provide a link to the issue: #509 
> 
> 
- The option ``--use_relative_path`` only covers fabric netlist generator
> 
>
> 
> 
> 
> - [ ] VPR
> - [ ] …
> Now Verilog Testbench Generator has a new option ``--use_relative_path``

- docs/source/manual/file_formats/bus_group_file.rst
- libopenfpga/libbusgroup/src/bus_group.cpp
- libopenfpga/libbusgroup/src/bus_group.h
- libopenfpga/libbusgroup/src/bus_group_xml_constants.h
- libopenfpga/libbusgroup/src/read_xml_bus_group.cpp
- libopenfpga/libbusgroup/src/write_xml_bus_group.cpp
- openfpga/src/fpga_verilog/verilog_preconfig_top_module.cpp
- openfpga/src/fpga_verilog/verilog_testbench_utils.cpp
- openfpga/src/fpga_verilog/verilog_writer_utils.cpp
- openfpga/src/fpga_verilog/verilog_writer_utils.h
- openfpga_flow/tasks/basic_tests/bus_group/full_testbench_explicit_mapping/config/counter8_bus_group.xml
- openfpga_flow/tasks/basic_tests/bus_group/full_testbench_implicit_mapping/config/counter8_bus_group.xml
- openfpga_flow/tasks/basic_tests/bus_group/preconfig_testbench_explicit_mapping/config/counter8_bus_group.xml
- openfpga_flow/tasks/basic_tests/bus_group/preconfig_testbench_implicit_mapping/config/counter8_bus_group.xml
> - [x] To address an existing issue. If so, please provide a link to the issue: #360 
> 
> 
- Bus group file only supports big-endian
>
> 
> 
> 
> - [ ] VPR
> …
> Bus support now support big-endian and little-endian

- openfpga_flow/tasks/basic_tests/bus_group/full_testbench_explicit_mapping/config/mac4_bus_group.xml
- openfpga_flow/tasks/basic_tests/bus_group/full_testbench_explicit_mapping/config/pin_constraints_dummy.xml
- openfpga_flow/tasks/basic_tests/bus_group/full_testbench_explicit_mapping/config/task.conf
- openfpga_flow/tasks/basic_tests/bus_group/full_testbench_implicit_mapping/config/mac4_bus_group.xml
- openfpga_flow/tasks/basic_tests/bus_group/full_testbench_implicit_mapping/config/pin_constraints_dummy.xml
- openfpga_flow/tasks/basic_tests/bus_group/full_testbench_implicit_mapping/config/task.conf
- openfpga_flow/tasks/basic_tests/bus_group/preconfig_testbench_explicit_mapping/config/mac4_bus_group.xml
- openfpga_flow/tasks/basic_tests/bus_group/preconfig_testbench_explicit_mapping/config/pin_constraints_dummy.xml
- openfpga_flow/tasks/basic_tests/bus_group/preconfig_testbench_explicit_mapping/config/task.conf
- openfpga_flow/tasks/basic_tests/bus_group/preconfig_testbench_implicit_mapping/config/mac4_bus_group.xml
- openfpga_flow/tasks/basic_tests/bus_group/preconfig_testbench_implicit_mapping/config/pin_constraints_dummy.xml
- openfpga_flow/tasks/basic_tests/bus_group/preconfig_testbench_implicit_mapping/config/task.conf
> - [x] To address an existing issue. If so, please provide a link to the issue: #360 
> 
> 
- Only output buses are validated in regression tests
>
> 
> 
- Validate input buses are validated in regression tests
- Validate that bus group file can be customized for each benchmark in task configuration file
> 
> - [ ] VPR
> - [ ] …
> More tests on Bus support: Validate its correctness on Input buses

- vpr/src/base/netlist_writer.cpp
> 
> <By default VPR netlist writer connects undriven output to X>
>
> <Change the default behavior to create an internal net for unconnected output as connecting to 1'bX will create compilation issues>
> 
> - [x ] VPR
> - [ ] Flow …
> Post layout netlist

- vpr/src/base/netlist_writer.cpp
> Bus outputs are left unconnected leading to compilation erros
>
> connect the floating output to internally generated nets
> 
> - [ X] VPR …
> Post layout

- libopenfpga/libopenfpgautil/src/openfpga_digest.cpp
… as Linux
Add support for OpenFPGA build on Windows 10 with MinGW-w64-g++
> 
> 
> 
Windows build for OpenFPGA fails only because of the redeclaration of variables in libopenfpga/libopenfpgautil/src/openfpga_digest.cpp
Fixing this will not change Linux behavior, but will enable Windows support as well.
> 
> 
>
> 
> 
> 
Add Windows MinGW-w64 build support for OpenFPGA
> 
> 
> 
> - [ ] …
> fix openfpga_digest functions to work on WIN32(MinGW-w64-g++) 

- openfpga/src/annotation/write_xml_device_rr_gsb.cpp
- openfpga/src/annotation/write_xml_device_rr_gsb.h
- openfpga/src/base/openfpga_write_gsb.cpp
> 
> 
- RR GSB only outputs rr_graph attributes, which is hard for PD team to sign-off. 
>
> 
> 
An example output:
> 
> - [ ] VPR
> - [ ] …
> [Engine] Now GSB output file contains segments name and pin name in SB module

- .gitignore
- Dockerfile
- docs/source/tutorials/getting_started/shell_shortcuts.rst
- openfpga.sh
- openfpga_flow/regression_test_scripts/basic_reg_test.sh
`create-task _task_copy basic_tests/generate_fabric`
Creates a copy of `basic_tests/generate_fabric` in the current directory with `_task_copy` name
Added CI tests also
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR
> ### Impact of the pull request
> …
> Added option to copy example projects

- vpr/src/base/read_route.cpp
Fix issues with the reworked format_ptc_num() function:
- off by one error after split with delimiter
- reusing same stringstream for multiple string to int conversions (clear before using again)
reworked format_ptc_num() function has some issues.
fix the logic in format_ptc_num() 
> 
> - [x] VPR `read_route.cpp`
> - …
> fix format_ptc_num() issues

- vpr/src/base/SetupVPR.cpp
- vpr/src/base/ShowSetup.cpp
- vpr/src/base/netlist_writer.cpp
- vpr/src/base/netlist_writer.h
- vpr/src/base/read_options.cpp
- vpr/src/base/read_options.h
- vpr/src/base/vpr_api.cpp
- vpr/src/base/vpr_types.h
We would like to update VPR with some features and fixes that were introduced in upstream VPR with PR https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/1789 and follow-up https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/2002
While VPR writes post-implementation verilog netlists, unconnected inputs are always tied to `1'b0` and outputs are connected to dummy nets.
>
* `--post_synth_netlist_unconn_inputs {unconnected, nets, gnd, vcc}`
* `--post_synth_netlist_unconn_outputs {unconnected, nets}`
> ### Which part of the code base require a …
> VPR: handle unconnected ports

- libopenfpga/libarchopenfpga/src/arch_direct.h
- libs/libvtrutil/src/vtr_small_vector.h
- vpr/src/place/place.cpp
Add support for OpenFPGA build on Windows 10/11 with MinGW-w64-g++
Windows build for OpenFPGA fails only because of the non inclusion of header files, that MinGW gcc cannot automatically pick.
Fixing this will not change Linux behavior, but will enable Windows support as well.
Add header includes where needed.
> 
> - [x] VPR
> - [ ] …
> Add support for (MinGW gcc) Windows build

- vpr/src/base/netlist_writer.cpp
- vpr/src/base/read_blif.cpp
- vpr/src/base/read_blif.h
We would like to update VPR with some features and fixes that were introduced in upstream VPR with PR https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/1663
Current version of VPR writes faulty post-implementation netlist because of EBLIF parameters misinterpretation (binary parameters are interpreted as decimal).
> This PR improves in the following aspects:
> ### Impact of the pull request
> VPR: validate EBLIF parameters and fix them in verilog netlist writer

- vpr/src/base/netlist_writer.cpp
Signed-off-by: Pawel Czarnecki <pczarnecki@antmicro.com>
> - [x] To address an existing issue.
In https://github.com/lnis-uofu/OpenFPGA/pull/700 I accidentally introduced unnecessary escapes to SDF writer for black box module instances. This caused inconsistency between simulation models and generated sdf files in simulations.
This PR fixes this by removing escapes.
> - [x] VPR
> VPR: netlist writer: sdf: don't escape '[' and ']' chars for black boxes

- vpr/src/base/atom_lookup.cpp
- vpr/src/base/atom_lookup.h
- vpr/src/timing/timing_graph_builder.cpp
- vpr/src/timing/timing_graph_builder.h
> - [x] To address an existing issue. If so, please provide a link to the issue: (none here)
> ### Technical details
This PR brings in some code from upstream VPR related to timing graph node ID remapping. The code contains fixes which resolve VPR crashes on writing post-pnr SDF files in presence of leaf pb_types that model input and output registers connected by an internal combinational path.
> 
> - [x] VPR
> - [ ] …
> Fixes for VPR timing node remapping

- docs/source/manual/openfpga_flow/run_fpga_task.rst
- openfpga_flow/regression_test_scripts/basic_reg_test.sh
- openfpga_flow/scripts/run_fpga_flow.py
- openfpga_flow/scripts/run_fpga_task.py
- openfpga_flow/tasks/basic_tests/fixed_simulation_settings/fixed_operating_clock_freq_no_ace/config/pin_constraints.xml
- openfpga_flow/tasks/basic_tests/fixed_simulation_settings/fixed_operating_clock_freq_no_ace/config/task.conf
> - [x] To address an existing issue. If so, please provide a link to the issue: #401 
> 
> 
> 
> 
> 
>
> 
> 
> 
> - [ ] VPR …
> Now .act file is no longer required in openfpga_flow/task when power analysis option is off

- libopenfpga/libpcf/src/base/io_location_map.h
- libopenfpga/libpcf/src/base/io_net_place.h
Add support for OpenFPGA build on Windows 10/11 with MinGW-w64-g++
Windows build for OpenFPGA fails only because of the non inclusion of header files, that MinGW gcc cannot automatically pick.
Fixing this will not change Linux behavior, but will enable Windows support as well.
Add header includes where needed.
> 
> - [ ] VPR
> - [ ] …
> add <array> include to fix compilation issues on Windows (MinGW x64 g++)

- openfpga/src/annotation/rr_gsb_writer_option.cpp
Add support for OpenFPGA build on Windows 10/11 with MinGW-w64-g++
Windows build for OpenFPGA fails only because of the non inclusion of header files, that MinGW gcc cannot automatically pick.
Fixing this will not change Linux behavior, but will enable Windows support as well.
Add header includes where needed.
> 
> - [ ] VPR
> - [ ] …
> add <array> declaration to fix gcc error

- docs/source/manual/arch_lang/addon_vpr_syntax.rst
- libs/libarchfpga/src/read_xml_arch_file.cpp
- openfpga_flow/regression_test_scripts/basic_reg_test.sh
- openfpga_flow/tasks/basic_tests/k4_series/k4n4_custom_io_loc/config/task.conf
- openfpga_flow/vpr_arch/README.md
- openfpga_flow/vpr_arch/k4_N4_tileable_customIoLoc_40nm.xml
> - [x] To address an existing issue. If so, please provide a link to the issue: #774 
> 
> 
> 
> 
> 
>
> 
> 
> 
> - [ ] VPR …
> Subtile syntax

- docs/source/manual/openfpga_shell/openfpga_commands/fpga_bitstream_commands.rst
- openfpga/src/base/openfpga_bitstream_command.cpp
- openfpga/src/base/openfpga_repack.cpp
- openfpga/src/repack/repack.cpp
- openfpga/src/repack/repack.h
- openfpga/src/repack/repack_option.cpp
- openfpga/src/repack/repack_option.h
- openfpga_flow/benchmarks/micro_benchmark/rst_on_lut/rst_on_lut.v
- openfpga_flow/openfpga_shell_scripts/ignore_global_nets_on_pins_example_script.openfpga
- openfpga_flow/regression_test_scripts/basic_reg_test.sh
- openfpga_flow/tasks/basic_tests/k4_series/k4n4_rstOnLut/config/pin_constraints_reset.xml
- openfpga_flow/tasks/basic_tests/k4_series/k4n4_rstOnLut/config/task.conf
- openfpga_flow/vpr_arch/README.md
- openfpga_flow/vpr_arch/k4_frac_N4_tileable_fracff_rstOnLut_40nm.xml
> 
> 
> 
> 
> 
>
> 
> 
> 
> - [ ] VPR
> - [x] Architecture library
> - [x] Regression tests …
> Test reset signal from a global network to drive an LUT input

- openfpga/src/fabric/build_fabric_io_location_map.cpp
- openfpga/src/fabric/build_grid_modules.cpp
- openfpga/src/fabric/build_top_module.cpp
- openfpga/src/fabric/build_top_module_directs.cpp
- openfpga/src/fabric/build_top_module_memory.cpp
- openfpga/src/fabric/build_top_module_memory_bank.cpp
- openfpga/src/fabric/module_manager.cpp
- openfpga/src/fabric/module_manager.h
- openfpga/src/utils/module_manager_utils.cpp
- openfpga_flow/tasks/basic_tests/k4_series/k4n4_custom_io_loc/config/task.conf
- openfpga_flow/vpr_arch/k4_N4_tileable_customIoLoc_40nm.xml
> 
> 
- OpenFPGA only supports I/Os placed on perimeter
>
> 
> 
> 
> - [ ] VPR
> - [ ] …
> Support I/Os in the center of the FPGA fabric

- .github/workflows/build.yml
- CMakeLists.txt
- docs/source/tutorials/getting_started/compile.rst
> 
> 
- We build all the modules/engines by default. And there are no options to skip any of them. This is not easy for integration, when OpenFPGA is used as a subsystem/submodule by another repo.
>
> 
> 
> 
> - [ ] VPR …
> Options to compile the codebase partially

- .github/workflows/build.yml
- CMakeLists.txt
- libs/libopenfpgautil/CMakeLists.txt
> 
> 
- version number is always rebuilt during each compilation, as the version number is the dependency of many libraries. This has causes a long build time when using OpenFPGA as a submodule
>
> 
> 
```
tangxifan@LAPTOP-CVNHOGSN:~/OpenFPGA$ ./build/openfpga/openfpga --version
Version: 
Revision: 
Compiled: 
Compiler: GNU 9.4.0 on …
```
> New option to bypass version build

- openfpga_flow/tasks/fpga_verilog/lut_design/single_mode/config/task.conf
- openfpga_flow/vpr_arch/k6_N10_tileable_40nm.xml
> - [x] To address an existing issue. If so, please provide a link to the issue: #694 
> 
> 
- We see inconsistency in some test cases where ``bb_cost_check`` breaks. The root of cause is that placer builds a wire lookahead map using the default routing resource graph generator rather than the tileable routing resource graph.
>
> 
> 
> 
> - [x] VPR
> - [ ] Tileable routing …
> Fix a bug where placer does not call tileable rr-graph generator

- .github/dependabot.yml
> - [x] To address an existing issue. If so, please provide a link to the issue: #832 
> 
> 
- VTR submodule has to be manually updated
>
> 
> 
- Enabled dependabot for VTR submodule
> 
> - [ ] VPR
> - [ ] …
> Enabled dependabot for VTR submodule

- openfpga_flow/openfpga_cell_library/verilog/frac_mult_36x36.v
Added new divisible 36x36 multiplier cell library for architectures which has fracturable dsp36:
- The 36x36 multiplier is form from sixteen 9x9 multipliers. 
- It operates same modes with existing library. It can operate in 3 modes: 
-  1. one 36-bit multiplier 
- 2. two 18-bit multipliers 
- 3. four 9-bit multipliers
- It provides ~%20 better area than existing cell library (mult_36x36.v) Comparison made with Synopsys Design Compiler NXT:
- mult_36x36.v           Total cell area     20470 um2
- frac_mult_36x36.v   Total cell area     15103 um2
> Added new cell library for fracturable dsp36

- libs/libpcf/src/base/pcf_data.cpp
> 
> 
> 
> 
> 
>
> 
> 
> 
> - [ ] VPR …
> Pcf hotfix - Avoid key collision when validating pcf data 

- libs/libopenfpgashell/src/shell.tpp
> 
> 
- Shell name is hardcoded in openfpga shell's ending messages. This will limit the use of openfpgashell in extension
>
> 
> 
> 
> - [ ] VPR
> - [ ] …
> Now OpenFPGA Shell can show customized name in ending messages

- docs/source/manual/openfpga_shell/openfpga_commands/vpr_commands.rst
- openfpga/src/vpr_wrapper/vpr_command.cpp
- openfpga/src/vpr_wrapper/vpr_main.cpp
- openfpga/src/vpr_wrapper/vpr_main.h
- openfpga_flow/openfpga_shell_scripts/vpr_standalone_example_script.openfpga
- openfpga_flow/regression_test_scripts/basic_reg_test.sh
- openfpga_flow/tasks/basic_tests/vpr_standalone/config/task.conf
> - [x] To address an existing issue. If so, please provide a link to the issue: #906 
> 
> 
- When vpr is run in OpenFPGA shell, it always keep results in memory. As a result, vpr cannot be called multiple time in OpenFPGA shell.
>
> 
> 
> 
> - [ ] VPR
> - [ ] …
> Now VPR can be run independently in OpenFPGA shell

- libs/libopenfpgashell/src/shell.tpp
- libs/libopenfpgautil/src/openfpga_tokenizer.cpp
- libs/libopenfpgautil/src/openfpga_tokenizer.h
> 
> 
- Currently the command line parsing for supporting quotes are in OpenFPGA shell (shell.tpp), which should be part of the generic tokenizer in openfpga utility library
>
> 
> 
- As titled
> 
> - [ ] VPR
> - [ ] …
> Cleanup: Move command string parsing to OpenFPGA Tokenizer

- libs/libopenfpgashell/src/shell.h
- libs/libopenfpgashell/src/shell.tpp
> 
> 
- Hidden commands are already not shown in help desk but they can still be called in both interactive mode and script mode in OpenFPGA shell, as long as the users know their existence. This will hurt and confuse many users, especially for commercial vendors who want to keep their scerets.
> 
> 
- As titled. 
- Developers can freely …
> Now hidden commands are not allowed to be called through interactive mode and script model in OpenFPGA shell

- openfpga/src/repack/repack.cpp
> 
> 
- Repacker skip some nets to be routed, when there are no regular routing traces found but there are invisible routing traces existing.
>
> 
> 
- Repacker will route the net when there are only invisible routing traces existing
> 
> - [ ] VPR
> - [ ] Tileable routing architecture …
> Fixed a bug in repack when only invisible routing sinks are … 

- .github/workflows/build.yml
- CMakeLists.txt
- docker/Dockerfile.master
- openfpga_flow/misc/fpgaflow_default_tool_path.conf
> 
> 
- Yosys binary was installed to source directory of yosys submodule. This is not a standard way. It causes trouble when creating  binary release for OpenFPGA.
>
> 
> 
> 
> - [ ] VPR
> - [ ] …
> Now Yosys binary is installed to build directory

- docs/source/manual/openfpga_shell/openfpga_commands/setup_commands.rst
- libs/libopenfpgautil/src/openfpga_reserved_words.h
- openfpga/src/base/openfpga_build_fabric_template.h
- openfpga/src/base/openfpga_naming.cpp
- openfpga/src/base/openfpga_naming.h
- openfpga/src/base/openfpga_setup_command_template.h
- openfpga/src/fabric/build_device_module.cpp
- openfpga/src/fabric/build_device_module.h
- openfpga/src/fabric/module_manager.cpp
- openfpga/src/fabric/module_manager.h
- openfpga/src/fpga_bitstream/build_device_bitstream.cpp
- openfpga/src/fpga_bitstream/build_fabric_bitstream.cpp
- openfpga/src/fpga_sdc/analysis_sdc_writer.cpp
- openfpga/src/fpga_sdc/pnr_sdc_writer.cpp
- openfpga/src/fpga_verilog/verilog_api.cpp
- openfpga/src/fpga_verilog/verilog_top_module.cpp
- openfpga/src/fpga_verilog/verilog_top_module.h
- openfpga_flow/openfpga_shell_scripts/fpga_core_example_script.openfpga
- openfpga_flow/openfpga_shell_scripts/generate_bitstream_example_script.openfpga
- openfpga_flow/openfpga_shell_scripts/generate_bitstream_fpga_core_example_script.openfpga
- openfpga_flow/openfpga_shell_scripts/write_full_testbench_fpga_core_example_script.openfpga
- openfpga_flow/regression_test_scripts/basic_reg_test.sh
- openfpga_flow/regression_test_scripts/fpga_bitstream_reg_test.sh
- openfpga_flow/tasks/basic_tests/full_testbench/fpga_core_wrapper/config/task.conf
- openfpga_flow/tasks/basic_tests/preconfig_testbench/fpga_core_wrapper/config/task.conf
- openfpga_flow/tasks/fpga_bitstream/generate_bitstream/fpga_core_wrapper/config/task.conf
> - [x] To address an existing issue. If so, please provide a link to the issue: #1220 
> 
> 
- Already detailed in #1220 
> 
> 
**Note that I/O customization is not yet supported. Will be addressed in a later PR**
> 
> - [ ] VPR
> - [x] FPGA-SDC
> …
> Support ``fpga_core`` wrapper insertion

- .github/workflows/cell_lib_test.yml
- .github/workflows/install_dependencies_run.sh
- .github/workflows/install_dependencies_run_ubuntu22p04.sh
> 
> 
- CI ``cell_library_test`` failed on the master branch [8cac776](https://github.com/lnis-uofu/OpenFPGA/commit/8cac776b2843d08c2e00557d07c16a7f7a0b174f)
>
> 
> 
- Migrate to Ubuntu 22.04.
**Later on, we will build compatibility to ubuntu 22.04!!!**
> 
> - [ ] VPR
> - [ ] Tileable routing …
> [ci] now cell lib test use ubunut 22.04

- openfpga/src/fpga_bitstream/write_text_fabric_bitstream.cpp
- openfpga/src/fpga_bitstream/write_xml_fabric_bitstream.cpp
> - [x] To address an existing issue. Follow up comment https://github.com/lnis-uofu/OpenFPGA/pull/1259
Technically this is not a bug fix, just to address comment from xifan from https://github.com/lnis-uofu/OpenFPGA/pull/1259 - even though personally I would think memset, memcpy, memcmp should be some most basic thing for those study software/programming and bit manipulation should be basic digital knowledge. 
> 
> - [ ] VPR …
> Address follow up from PR 1259

- openfpga/src/annotation/fabric_tile.cpp
- openfpga/src/fabric/build_tile_modules.cpp
- openfpga_flow/regression_test_scripts/basic_reg_test.sh
- openfpga_flow/tasks/basic_tests/group_config_block/group_config_block_homo_fabric_tile_Lshape/config/task.conf
- openfpga_flow/tasks/basic_tests/group_config_block/group_config_block_homo_fabric_tile_Lshape/config/tile_config.xml
- openfpga_flow/vpr_arch/k4_N4_tileableL_40nm.xml
> 
> 
- When the following options are enabled for a given FPGA fabric in L shape, fabric generation failed.
- ``group_tile``
- ``group_config_block``
- ``shrink_boundary``
>
> 
> 
> 
> - [ ] VPR
> …
> Fixed a bug when Combo options are enabled: ``group_tile``, ``group_config_block`` and ``shrink_boundary``

- openfpga/src/fabric/build_top_module_child_fine_grained_instance.cpp
- openfpga_flow/regression_test_scripts/basic_reg_test.sh
- openfpga_flow/tasks/basic_tests/tile_organization/io_subtile_strong/config/task.conf
- openfpga_flow/vpr_arch/k4_N4_tileable_IoSubtile_40nm.xml
> 
> 
- When trying to customize pin location for subtiles, the subtile index cannot be used. 
For example,
```
<tile name="hybrid_io_tile_center" area="0">
<sub_tile name="fpga_input_center" capacity="6">
<equivalent_sites>
<site pb_type="fpga_input"/>
</equivalent_sites>
<output name="inpad" num_pins="1"/>
<fc in_type="frac" in_val="0.15" out_type="frac" out_val="0.10"/>
<pinlocations pattern="custom">
<loc …
```
> Now Subtile index is supported in Custom Pin Location

- openfpga/src/fabric/build_top_module_child_fine_grained_instance.cpp
- openfpga/src/fabric/build_top_module_child_tile_instance.cpp
- openfpga/src/utils/check_tile_annotation.cpp
- openfpga_flow/openfpga_arch/k4_N4_40nm_GlobalTileClk_registerable_io_cc_openfpga.xml
- openfpga_flow/regression_test_scripts/basic_reg_test.sh
- openfpga_flow/tasks/basic_tests/global_tile_ports/global_tile_clock_subtile/config/task.conf
- openfpga_flow/tasks/basic_tests/group_config_block/group_config_block_homo_fabric_tile_global_tile_clock_io_subtile/config/task.conf
- openfpga_flow/tasks/basic_tests/group_config_block/group_config_block_homo_fabric_tile_global_tile_clock_io_subtile/config/tile_config.xml
- openfpga_flow/tasks/basic_tests/tile_organization/fabric_tile_global_tile_clock_io_subtile/config/task.conf
- openfpga_flow/tasks/basic_tests/tile_organization/fabric_tile_global_tile_clock_io_subtile/config/tile_config.xml
- openfpga_flow/vpr_arch/k4_N4_tileable_GlobalTileClk_registerable_io_40nm.xml
> 
> 
- See more bugs in Subtile support when the global tile clock feature is on:
Example architecture: 
```
<tile name="io_hybrid" area="0">
<sub_tile name="io_input" capacity="2">
<equivalent_sites>
<site pb_type="io_input"/>
</equivalent_sites>
<output name="inpad" num_pins="1"/>
<clock name="clk" num_pins="1"/>
<fc in_type="frac" in_val="0.15" out_type="frac" out_val="0.10">
<fc_override port_name="clk" fc_type="frac" …
```
> Fixed a bug on spotting pin index of subtiles

- openfpga_flow/openfpga_arch/k4_frac_N4_adder_chain_mem1K_L124X_L12Y_40nm_frame_openfpga.xml
- openfpga_flow/regression_test_scripts/basic_reg_test.sh
- openfpga_flow/tasks/basic_tests/k4_series/k4n4_chandistr/config/task.conf
- openfpga_flow/tasks/basic_tests/k4_series/k4n4_chandistr_segdist/config/task.conf
- openfpga_flow/vpr_arch/k4_frac_N4_tileable_adder_chain_mem1K_L124X_L12Y_ChanWidth0p8_40nm.xml
- openfpga_flow/vpr_arch/k4_frac_N4_tileable_adder_chain_mem1K_L124_ChanWidth0p8_40nm.xml
> 
> 
- VPR supports different routing channel width in X and Y axis. For example, X-direction routing channel width is 30 while Y-direction routing channel width is 20. This is very useful to alleviate routing congestion when some programmable blocks have a large number of pins to access routing on some sides.
- VPR also support different wire distribution in X and Y axis routing channels. For example, X-direction routing …
> Support different routing channel width in X and and Y axis

- openfpga/src/annotation/annotate_rr_graph.cpp
- openfpga/src/annotation/device_rr_gsb.cpp
- openfpga/src/annotation/device_rr_gsb.h
- openfpga/src/annotation/fabric_tile.cpp
- openfpga/src/base/openfpga_build_fabric_template.h
- openfpga/src/fabric/build_device_module.cpp
- openfpga/src/fabric/build_fabric_tile.cpp
- openfpga/src/fabric/build_fabric_tile.h
- openfpga/src/fabric/build_routing_modules.cpp
- openfpga/src/fabric/build_tile_modules.cpp
- openfpga/src/fabric/build_top_module_child_fine_grained_instance.cpp
- openfpga/src/fabric/build_top_module_child_tile_instance.cpp
- openfpga/src/fabric/build_top_module_connection.cpp
- openfpga/src/fabric/build_top_module_memory.cpp
- openfpga/src/fabric/build_top_module_memory.h
- openfpga/src/fpga_bitstream/build_routing_bitstream.cpp
- openfpga/src/fpga_sdc/analysis_sdc_routing_writer.cpp
- openfpga/src/fpga_sdc/pnr_sdc_routing_writer.cpp
- openfpga/src/fpga_sdc/pnr_sdc_writer.cpp
- openfpga/src/fpga_sdc/sdc_hierarchy_writer.cpp
- openfpga/src/fpga_sdc/sdc_hierarchy_writer.h
- openfpga/src/fpga_spice/spice_api.cpp
- openfpga/src/fpga_spice/spice_routing.cpp
- openfpga/src/fpga_spice/spice_routing.h
- openfpga/src/fpga_verilog/verilog_api.cpp
- openfpga/src/fpga_verilog/verilog_routing.cpp
- openfpga/src/fpga_verilog/verilog_routing.h
- openfpga/src/utils/device_rr_gsb_utils.cpp
- openfpga/src/utils/device_rr_gsb_utils.h
> 
> 
- Some empty tiles are seen when the ``shrink_boundary`` option of tileable rr_graph builder is enabled. See the red circle in the following figure.
> 
> 
> 
> - [x] VPR …
> No more empty tiles on edges when Shrink Boundary is enabled

- openfpga/src/fabric/build_tile_modules.cpp
- openfpga/src/fabric/build_top_module_child_tile_instance.cpp
- openfpga_flow/tasks/basic_tests/module_naming/using_index/config/task.conf
> 
> 
- In the tile modules, the names of ports have to be unique. However, when the option ``--name_module_using_index`` is enabled, the port name includes a prefix of unique SB/CB modules, to indicate the source of the port (in the context of subblocks inside the tile). However, this may cause naming conflicts when there are multiple same SB/CB modules in the same tile.
>
> 
> 
This …
> Now use relative index to name module ports of tile modules

- openfpga/src/fabric/build_grid_modules.cpp
- openfpga/src/fabric/build_memory_modules.cpp
- openfpga/src/fabric/build_memory_modules.h
- openfpga/src/fabric/build_routing_modules.cpp
- openfpga/src/fpga_verilog/verilog_routing.cpp
> - [x] To address an existing issue. If so, please provide a link to the issue: #1415 
> 
> 
> 
> 
As stated in #1415
>
> 
> 
> 
> - [ ] VPR
> - [ ] …
> Fixed the bugs on module names using index

- docs/source/manual/openfpga_shell/openfpga_commands/fpga_verilog_commands.rst
- openfpga/src/base/openfpga_verilog_command_template.h
- openfpga/src/base/openfpga_verilog_template.h
- openfpga/src/fpga_verilog/verilog_api.cpp
- openfpga/src/fpga_verilog/verilog_api.h
- openfpga/src/fpga_verilog/verilog_preconfig_top_module.cpp
- openfpga/src/fpga_verilog/verilog_preconfig_top_module.h
- openfpga/src/fpga_verilog/verilog_preconfig_top_module_utils.cpp
- openfpga/src/fpga_verilog/verilog_preconfig_top_module_utils.h
- openfpga/src/fpga_verilog/verilog_template_testbench.cpp
- openfpga/src/fpga_verilog/verilog_template_testbench.h
- openfpga/src/fpga_verilog/verilog_testbench_io_connection.cpp
- openfpga/src/fpga_verilog/verilog_testbench_io_connection.h
- openfpga/src/fpga_verilog/verilog_testbench_options.cpp
- openfpga/src/fpga_verilog/verilog_testbench_options.h
- openfpga_flow/openfpga_shell_scripts/write_testbench_template_example_script.openfpga
- openfpga_flow/regression_test_scripts/basic_reg_test.sh
- openfpga_flow/tasks/basic_tests/generate_template_testbench/config/counter8_bus_group.xml
- openfpga_flow/tasks/basic_tests/generate_template_testbench/config/mac4_bus_group.xml
- openfpga_flow/tasks/basic_tests/generate_template_testbench/config/pin_constraints_dummy.xml
- openfpga_flow/tasks/basic_tests/generate_template_testbench/config/pin_constraints_reset.xml
- openfpga_flow/tasks/basic_tests/generate_template_testbench/config/task.conf
> - [x] To address an existing issue. If so, please provide a link to the issue: #1425 
> 
> 
- As stated in #1425 
> 
> 
>
> 
> 
-  a new command ``write_testbench_io_connection`` will be added with the following option
- a new command ``write_testbench_template`` will be added with the following option
> 
> - [ ] VPR
> - [ ] OpenFPGA …
> Support testbench template generation and I/O connection generation

- openfpga/src/fpga_verilog/verilog_top_testbench.cpp
- openfpga/src/utils/fabric_bitstream_utils.cpp
> - [x] To address an existing issue. If so, please provide a link to the issue: #1140 
> 
> 
- When there are more than 1 programming clocks, there is a bug in the full testbench, where a complete bitstream has to be loaded more than once. In other words, when each programming clock is on, full bitstream size has to be given for the configuration chains.
>
> 
> 
- The restrictions have now been removed. Only part of the bitstream can …
> Fixed the bug where the full testbench has to load longest bitstream for each chain in CCFF v2.0 

- .github/workflows/build.yml
- Makefile
- docs/source/manual/arch_lang/addon_vpr_syntax.rst
- docs/source/manual/arch_lang/figures/concat_pass_wire.svg
- docs/source/manual/arch_lang/figures/concat_wire.svg
- docs/source/manual/arch_lang/figures/opin2all_sides.svg
- openfpga_flow/regression_test_scripts/fpga_verilog_reg_test.sh
- openfpga_flow/tasks/fpga_verilog/lut_design/single_mode/config/task.conf
- openfpga_flow/tasks/fpga_verilog/rr_concat_wire/config/bus_group_gen.py
- openfpga_flow/tasks/fpga_verilog/rr_concat_wire/config/counter8_bus_group_task.yaml
- openfpga_flow/tasks/fpga_verilog/rr_concat_wire/config/pin_constraints_reset.xml
- openfpga_flow/tasks/fpga_verilog/rr_concat_wire/config/task.conf
- openfpga_flow/vpr_arch/README.md
- openfpga_flow/vpr_arch/k4_N4_tileable_40nm.xml
- openfpga_flow/vpr_arch/k4_frac_N4_tileable_adder_chain_40nm.xml
- openfpga_flow/vpr_arch/k6_N10_tileable_40nm.xml
- openfpga_flow/vpr_arch/k6_frac_N10_tileableConcatWire_adder_chain_dpram8K_dsp36_fracff_40nm.xml
- openfpga_flow/vpr_arch/k6_frac_N10_tileable_adder_chain_dpram8K_dsp36_40nm.xml
- openfpga_flow/vpr_arch/k6_frac_N10_tileable_adder_chain_dpram8K_dsp36_fracff_40nm.xml
- openfpga_flow/vpr_arch/k6_frac_N10_tileable_adder_register_scan_chain_depop50_40nm.xml
> - [ ] To address an existing issue. If so, please provide a link to the issue: #1249 
> 
> 
- As stated in the issue
>
> 
> 
> 
> - [ ] VPR
> - [ ] …
> Upgrade VTR to resolve the bugs in tileable routing architecture

- openfpga/src/fpga_bitstream/write_text_fabric_bitstream.cpp
> - [x] To address an existing issue. If so, please provide a link to the issue: [1466](https://github.com/lnis-uofu/OpenFPGA/issues/1466)
The option boolean was accidentally reverted (See issue to know which changes cause the reversion) 
>
Revert back the boolean to correct one
> 
> - [ ] VPR
> - [ ] …
> Issue:1466 - Fix WL ordering in bitstream generation

- docs/source/manual/openfpga_shell/openfpga_commands/fpga_verilog_commands.rst
- openfpga/src/base/openfpga_verilog_command_template.h
- openfpga/src/base/openfpga_verilog_template.h
- openfpga/src/fpga_verilog/verilog_testbench_options.cpp
- openfpga/src/fpga_verilog/verilog_testbench_options.h
- openfpga/src/fpga_verilog/verilog_top_testbench.cpp
- openfpga/src/fpga_verilog/verilog_top_testbench_memory_bank.cpp
- openfpga/src/fpga_verilog/verilog_top_testbench_memory_bank.h
- openfpga_flow/openfpga_shell_scripts/write_full_testbench_simulator_support_example_script.openfpga
- openfpga_flow/regression_test_scripts/basic_reg_test.sh
- openfpga_flow/tasks/basic_tests/full_testbench/ql_memory_bank_shift_register_vcs/config/task.conf
> - [x] To address an existing issue. If so, please provide a link to the issue: #1274 
> 
> 
- As stated in #1274 
When apply the changes to full testbench as in #1274, we see errors in iVerilog simulation.
So, there are difference in simulators when interpreting Verilog codes.
>
> 
> 
> 
> - [ ] VPR
> - [x] …
> Support VCS simulator for QL memory bank in full testbench

- .github/workflows/build.yml
- .github/workflows/cell_lib_test.yml
- .github/workflows/format.yaml
> 
> 
- Node16 is going to be deprecated soon by the end of June 2024. See details at [link](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)
- When looking into our [ci flow warnings](https://github.com/lnis-uofu/OpenFPGA/actions/runs/9649881225),  a large number of warning are related to Node16. 
>
> 
> 
This PR improves in the following …
> Use a new version of cancel-previous-flow due to node16 deprecation

- libs/libfabrickey/test/fabric_key_assistant.cpp
> 
> 
- Fabric key assistant only reports the missing key in the input key against the reference key. However, it is very useful to report the reverse one: the missing key in the reference key against the input key
>
> 
> 
- Now when the missing key in the input key is detected, The the missing key in the reference key against the input key …
> [lib] now fabric key assistant can cross-check mismatches between reference and input fabric keys

- docs/source/manual/file_formats/clock_network.rst
- openfpga/src/utils/openfpga_physical_tile_utils.cpp
- openfpga_flow/openfpga_arch/k4_N4_40nm_ClkNtwk_registerable_IoSubtile_cc_openfpga.xml
- openfpga_flow/regression_test_scripts/basic_reg_test.sh
- openfpga_flow/tasks/basic_tests/tile_organization/fabric_tile_clkntwk_registerable_io_subtile/config/clk_arch_1clk_2layer.xml
- openfpga_flow/tasks/basic_tests/tile_organization/fabric_tile_clkntwk_registerable_io_subtile/config/task.conf
- openfpga_flow/tasks/basic_tests/tile_organization/fabric_tile_clkntwk_registerable_io_subtile/config/tile_config.xml
- openfpga_flow/vpr_arch/k4_N4_tileable_PerimeterCb_ClkNtwk_registerable_IoSubtile_40nm.xml
> 
> 
- When there are subtiles, it requires users to fill the clock tap in clock network with subtile name. 
However, in practice, the subtiles may share names across tiles. A better way is to use the tile name and subtile index. 
>
> 
> 
> 
> - [ ] VPR
> - [ ] Tileable routing architecture …
> Fixed a bug where clock network taps cannot identify subtiles

- openfpga/src/base/openfpga_pb_pin_fixup.cpp
- openfpga/src/base/openfpga_pb_pin_fixup.h
- openfpga/src/base/openfpga_pb_pin_fixup_template.h
- openfpga/src/fpga_bitstream/build_routing_bitstream.cpp
- openfpga_flow/openfpga_shell_scripts/example_clkntwk_pb_pin_fixup_no_ace_script.openfpga
- openfpga_flow/regression_test_scripts/basic_reg_test.sh
- openfpga_flow/tasks/basic_tests/clock_network/homo_1clock_1reset_2layer_on_lut_pb_pin_fixup/config/clk_arch_1clk_1rst_2layer.xml
- openfpga_flow/tasks/basic_tests/clock_network/homo_1clock_1reset_2layer_on_lut_pb_pin_fixup/config/pin_constraints_clk.xml
- openfpga_flow/tasks/basic_tests/clock_network/homo_1clock_1reset_2layer_on_lut_pb_pin_fixup/config/pin_constraints_rst.xml
- openfpga_flow/tasks/basic_tests/clock_network/homo_1clock_1reset_2layer_on_lut_pb_pin_fixup/config/pin_constraints_rst_and_clk.xml
- openfpga_flow/tasks/basic_tests/clock_network/homo_1clock_1reset_2layer_on_lut_pb_pin_fixup/config/repack_pin_constraints.xml
- openfpga_flow/tasks/basic_tests/clock_network/homo_1clock_1reset_2layer_on_lut_pb_pin_fixup/config/task.conf
> 
> 
- The ``pb_pin_fixup`` command does not cover global nets, such as clock and reset. These nets may be dropped during routing, resulting in no routing traces to be found. Meanwhile, these nets are mapped to pins by packer. So these nets were not remapped to any pin after routing. This causes some benchmarks which require clock and reset to drive LUTs to fail.
>
> 
> 
This PR …
> support global net fixup in pb pin fixup

- docs/source/manual/openfpga_shell/openfpga_commands/setup_commands.rst
- openfpga/src/base/openfpga_pb_pin_fixup.cpp
- openfpga/src/base/openfpga_pb_pin_fixup.h
- openfpga/src/base/openfpga_pb_pin_fixup_template.h
- openfpga/src/base/openfpga_setup_command_template.h
- openfpga_flow/openfpga_shell_scripts/example_clkntwk_pb_pin_fixup_no_ace_script.openfpga
- openfpga_flow/regression_test_scripts/basic_reg_test.sh
- openfpga_flow/tasks/basic_tests/clock_network/homo_1clock_1reset_2layer_on_lut_pb_pin_fixup_msb/config/clk_arch_1clk_1rst_2layer.xml
- openfpga_flow/tasks/basic_tests/clock_network/homo_1clock_1reset_2layer_on_lut_pb_pin_fixup_msb/config/pin_constraints_clk.xml
- openfpga_flow/tasks/basic_tests/clock_network/homo_1clock_1reset_2layer_on_lut_pb_pin_fixup_msb/config/pin_constraints_rst.xml
- openfpga_flow/tasks/basic_tests/clock_network/homo_1clock_1reset_2layer_on_lut_pb_pin_fixup_msb/config/pin_constraints_rst_and_clk.xml
- openfpga_flow/tasks/basic_tests/clock_network/homo_1clock_1reset_2layer_on_lut_pb_pin_fixup_msb/config/repack_pin_constraints.xml
- openfpga_flow/tasks/basic_tests/clock_network/homo_1clock_1reset_2layer_on_lut_pb_pin_fixup_msb/config/task.conf
> 
> 
- When ``--clock_modeling ideal`` is selected when running VPR, global nets will not be routed and their pin mapping on programmable blocks may be revoked by other nets due to optimization. Therefore, this command will restore the pin mapping for the global nets and pick a spare pin on programmable blocks. 
- Currently, when selecting the proper pin for mapping, the first found spare *Least Significant Bit* (LSB) will be …
> A new option '--map_global_net_to_msb' for command 'pb_pin_fixup'

- openfpga/src/annotation/annotate_rr_graph.cpp
- openfpga/src/annotation/openfpga_annotate_routing.cpp
- openfpga/src/annotation/openfpga_annotate_routing.h
- openfpga/src/base/openfpga_link_arch_template.h
- openfpga/src/mux_lib/mux_library_builder.cpp
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR …
> Enable bitstream generation with flat routing

- docs/source/manual/file_formats/bitstream_setting.rst
- libs/libarchopenfpga/src/bitstream_setting.cpp
- libs/libarchopenfpga/src/bitstream_setting.h
- libs/libarchopenfpga/src/bitstream_setting_fwd.h
- libs/libarchopenfpga/src/read_xml_bitstream_setting.cpp
- libs/libarchopenfpga/src/read_xml_openfpga_arch_utils.cpp
- libs/libarchopenfpga/src/read_xml_openfpga_arch_utils.h
- libs/libarchopenfpga/src/read_xml_pb_type_annotation.cpp
- libs/libarchopenfpga/src/write_xml_bitstream_setting.cpp
- libs/libopenfpgacapnproto/gen/unique_blocks_uxsdcxx.capnp
- openfpga/src/annotation/annotate_bitstream_setting.cpp
- openfpga/src/annotation/annotate_bitstream_setting.h
- openfpga/src/annotation/annotate_pb_types.cpp
- openfpga/src/annotation/vpr_bitstream_annotation.cpp
- openfpga/src/annotation/vpr_bitstream_annotation.h
- openfpga/src/annotation/vpr_device_annotation.cpp
- openfpga/src/annotation/vpr_device_annotation.h
- openfpga/src/base/openfpga_link_arch_template.h
- openfpga_flow/regression_test_scripts/fpga_bitstream_reg_test.sh
- openfpga_flow/tasks/fpga_bitstream/overload_default_mode_bit/config/bitstream_annotation.xml
- openfpga_flow/tasks/fpga_bitstream/overload_default_mode_bit/config/task.conf
> 
> 
- The mode-selection bits ``mode_bits`` of any ``pb_type`` can only be defined through the OpenFPGA architecture description file.  See details at [link](https://openfpga.readthedocs.io/en/master/manual/arch_lang/annotate_vpr_arch/#cmdoption-arg-circuit_model_name)
- In practice, we need different sets of mode_bits for unused/unmapped pb_types, when performing sign-off on an FPGA fabric. During the sign-off stage, OpenFPGA …
> Support overwriting mode_bits for pb_type through bitstream setting file

- CMakeLists.txt
- libs/libini/CMakeLists.txt
> 
> 
- CMake minimum requirements was 2.8.12. As now ubuntu 22.04 employs CMake 4.0, the minimum requirement bar is increased to 3.5. https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html
>
> 
> 
> 
> - [ ] VPR
> - [ ] OpenFPGA …
> [core] update cmake min version requirement to 3.5

- openfpga/src/fabric/build_mux_modules.cpp
- openfpga_flow/regression_test_scripts/fpga_verilog_reg_test.sh
- openfpga_flow/tasks/fpga_verilog/mux_design/stdcell_mux2_last_stage_size2/config/task.conf
> 
> 
- When the last stage of a MUX circuit model is defined to be different, a bug may arise when
- The last stage MUX is also driven by an input of the MUX. This happens to some single-level MUX or special MUX tree
For example
```
// ----- Verilog module for sb_mux_size2 -----
module sb_mux_size2(in,
sram,
sram_inv,
out);
//----- INPUT PORTS -----
input [0:1] in;
//----- INPUT PORTS -----
input [0:1] sram;
//----- INPUT PORTS …
```
> Fixed the bug where last stage MUX standard cell may be disconnected from MUX inputs

- .github/workflows/build.yml
- docs/source/manual/arch_lang/annotate_vpr_arch.rst
- docs/source/manual/file_formats/bitstream_setting.rst
- docs/source/tutorials/getting_started/compile.rst
- libs/libarchopenfpga/src/read_xml_openfpga_arch_utils.cpp
- libs/libopenfpgautil/src/openfpga_bits_parser.cpp
- libs/libopenfpgautil/src/openfpga_bits_parser.h
- openfpga_flow/openfpga_arch/README.md
- openfpga_flow/openfpga_arch/k4_frac_N4_fracff2edge_40nm_cc_BinModeBits_openfpga.xml
- openfpga_flow/openfpga_arch/k4_frac_N4_fracff2edge_40nm_cc_HexModeBits_openfpga.xml
- openfpga_flow/regression_test_scripts/basic_reg_test.sh
- openfpga_flow/tasks/basic_tests/mode_bit_format/bin_format_big_endian/config/pin_constraints_reset.xml
- openfpga_flow/tasks/basic_tests/mode_bit_format/bin_format_big_endian/config/task.conf
- openfpga_flow/tasks/basic_tests/mode_bit_format/hex_format_big_endian/config/pin_constraints_reset.xml
- openfpga_flow/tasks/basic_tests/mode_bit_format/hex_format_big_endian/config/task.conf
> - [x] To address an existing issue. If so, please provide a link to the issue: #1979 
> 
> 
As stated in #1979 
> 
> 
>
> 
> 
> 
> - [ ] VPR
> - [x] …
> Support HEX and BIN format with little/big endian for mode bits in architecture description

- .github/workflows/build.yml
- .gitmodules
- CMakeLists.txt
- docs/source/tutorials/getting_started/compile.rst
- openfpga_flow/benchmarks/micro_benchmark/and2/and2.sv
- openfpga_flow/benchmarks/micro_benchmark/and2_latch/and2_latch.sv
- openfpga_flow/misc/ys_tmpl_yosys_sv_vpr_flow.ys
- openfpga_flow/regression_test_scripts/basic_reg_test.sh
- openfpga_flow/tasks/basic_tests/systemverilog/config/task.conf
> 
> 
Currently, OpenFPGA only supports Verilog-2005 due to Yosys's limited support.
Recently, the Yosys-slang comes to the stage as an optional plug-in, offering good SystemVerilog support.
https://github.com/povik/yosys-slang
https://github.com/open-source-eda-birds-of-a-feather/open-source-eda-birds-of-a-feather.github.io/blob/main/doc/slides_2025/yosys-slang-dac-bof.pdf
>
> 
> 
> ### Which …
> Add SystemVerilog Frontend
