.travis/verilog_reg_test.sh, libopenfpga/libarchopenfpga/src/check_circuit_library.cpp, openfpga/src/base/openfpga_naming.cpp, openfpga/src/fpga_spice/spice_essential_gates.cpp, openfpga/src/fpga_verilog/verilog_essential_gates.cpp, openfpga/src/fpga_verilog/verilog_grid.cpp, openfpga/src/utils/circuit_library_utils.cpp, openfpga/src/utils/circuit_library_utils.h, openfpga_flow/fabric_keys/k4_N4_2x2_sample_key.xml, openfpga_flow/openfpga_arch/README.md, openfpga_flow/openfpga_arch/k4_N4_40nm_powergate_frame_openfpga.xml, openfpga_flow/tasks/power_gated_design/power_gated_inverter/config/task.conf
- Power-gating inverter/buffer support is now online. Dedicated tests are added to CI
- SPICE support update on power-gating inverter/buffer
- Refactored check codes to report errors early to users
- Formalize names of modules, instance and netlists to be consistent
- Splitted logical tile netlists where each netlist contains only one pb_type definition, in order to ease PnR scripts
=> Misc Updates

.travis/fpga_verilog_reg_test.sh, openfpga/src/base/openfpga_pb_pin_fixup.cpp, openfpga/src/repack/repack.cpp, openfpga_flow/openfpga_arch/k4_N4_no_local_routing_40nm_frame_openfpga.xml, openfpga_flow/tasks/fpga_verilog/fully_connected_output_crossbar/config/task.conf, openfpga_flow/tasks/fpga_verilog/no_local_routing/config/task.conf, openfpga_flow/vpr_arch/k4_N4_tileable_full_output_crossbar_40nm.xml, openfpga_flow/vpr_arch/k4_N4_tileable_no_local_routing_40nm.xml
Verified test cases & bug fix for flexible local routing architectures:
- No local routing architecture (only direct connections)
- Fully connected output crossbar
=> Support on flexible local routing architecture

openfpga_flow/scripts/run_fpga_flow.py
Bug fixes for 
```
python3 ./openfpga_flow/scripts/run_fpga_flow.py ./openfpga_flow/vpr_arch/k4_frac_N4_40nm.xml 
./openfpga_flow/benchmarks/pipelined_8bit_adder/pipelined_8bit_adder.v  --top_module pipelined_8bit_adder  
--disp
```
=> FLOW:  fixed display flag

README.md, docs/source/manual/arch_lang/circuit_model_examples.rst, docs/source/overview/tech_highlights.rst
- Add links to technical highlights
- Fix dead link to OpenFPGA logo in frontpage README
=> Documentation update

README.md
- Update README with latest Github Action badge
- Remove the Travis badge
=> Update README with latest Github Action badge

.github/labeler.yml, .github/workflows/labeler.yml
There was not labeler for pull requests.
Github should be able to create labels automatically based on which part of codes are changed
=> [Git] Add labeler for pull requests

README.md
**Address issue #161 **
Fix the deadlink by pointing to the right webpage in documentation
** No touch to the modules**
=> Dead link patch to fontpage README

docs/source/dev_manual/ci_cd_setup/index.rst, docs/source/dev_manual/index.rst, docs/source/index.rst
---
name: Added CI/CD docs
---
- What is currently done? (Provide issue link if applicable): Missing CI/CD implementation documentation
- What does this pull request change? Added CI/CD docs
=> [Docs] Added CI/CD docs

docs/source/manual/openfpga_shell/launch_openfpga_shell.rst, docs/source/manual/openfpga_shell/openfpga_commands/basic_commands.rst, openfpga/src/base/basic_command.cpp, openfpga/src/base/openfpga_title.cpp, openfpga/src/base/openfpga_title.h, openfpga/src/main.cpp
To address issue #193 
- 
This PR brings two changes on displaying version information
- Version information will not be show at the starting openfpga shell. Instead, users can call `--version`` or ``-v`` option when launching openfpga shell.
```
../openfpga/openfpga -v
Version: 1.0.0-dev+487bcd67-dirty
Revision: 487bcd67-dirty
Compiled: 2021-01-27T16:01:36
Compiler: GNU 8.4.0 on Linux-3.10.0-1127.18.2.el7.x86_64 x86_64
Build Info: debug ASSERT_LEVEL=2
```
- Openfpga shell has a new command ``version`` to display version information inside the shell. For example
```
../openfpga/openfpga -i
Start interactive mode of OpenFPGA...
___                   _____ ____   ____    _     
/ _ \ _ __ …
```
=> Version Echo of OpenFPGA Shell

.dockerignore, .github/workflows/build.yml, docker/Dockerfile.master
---
---
- What is currently done? (Provide issue link if applicable) In master branch docker fails to build the image to upload as a release 
- What does this pull request change? This fixes the bug (which was due to missing context during the docker build)
The test actions run is here  (the workfile used has a minor change to avoid updating existing master branch copy)
https://github.com/lnis-uofu/OpenFPGA/actions/runs/519608785
=> Bug fix on Docker build and upload on master

.github/workflows/build.yml
---
name: Checking master branch in change_detect
---
Described in #204 
=> [CICD] Checking master branch in change_detect

.github/workflows/build.yml
---
---
`docker_distribution` run of actions only used to run on master branch. Making it little tedious to test modification in that run from any other branch.
This Pull changes that and `docker_distribution` on any other branch as well, but it wont push to docker packages.
It allows full testing of actions flow before actually merging with master.
=> Checking complete flow of build.yml from non master branch 

openfpga_flow/misc/quicklogic_yosys_flow_ap3_adder.ys
---
---
@lnsharma : Bumping up Yosys submodule latest changes related to adder tech mapping. Also adding a yosys custom script to run yosys with adder inference.
- [*] FPGA-Verilog
=> Bumping up latest yosys changes related to adder tech mapping

openfpga.sh, openfpga_flow/misc/fpgaflow_default_tool_path.conf, openfpga_flow/scripts/run_fpga_flow.py, openfpga_flow/scripts/run_fpga_task.py, requirements.txt
---
Removed deadcode from fpga_clow  and fpga_rask scripts 
---
=> [Cleanup] Removed deadcode

.github/workflows/basic_reg_test.sh, .github/workflows/fpga_sdc_reg_test.sh, openfpga_flow/scripts/run_fpga_task.py
- What is currently done? (Provide issue link if applicable) Solves #209 
- What does this pull request change? Updates the task execution script
=> [Flow] Support multi-user environment for running task

docs/source/tutorials/compile.rst, docs/source/tutorials/index.rst, docs/source/tutorials/shell_shortcuts.rst, openfpga.sh
=> [Docs] Added documentation for docker based run and shell shortcuts documentation 

openfpga_flow/openfpga_shell_scripts/quicklogic_flow_example_script.openfpga, openfpga_flow/scripts/run_fpga_flow.py, openfpga_flow/tasks/quicklogic_tests/flow_test/config/task.conf
---
---
- [x ] To address an existing issue. If so, please provide a link to the issue.
While remove the dependency on activity file, yosys output has to be renamed to work with existing script, otherwise existing flow breaks if power_analysis option is turned off 
Copy the yosys output file to another file expected by .openfpga script
Change existing testcase to turn off power analysis and remove dependency on activity file
- [ x] Flow scripts
- [x ] Require new tests to be added
=> Tpagarani dev

openfpga_flow/regression_test_scripts/fpga_verilog_reg_test.sh
This is a follow-up PR for #227 which deploys the synthesizable verilog test case to CI
=> Deploy synthesizable verilog test to CI

openfpga_flow/misc/qlf_yosys.ys, openfpga_flow/openfpga_shell_scripts/quicklogic_flow_example_script.openfpga, openfpga_flow/tasks/quicklogic_tests/flow_test/config/task.conf
---
---
Bump up yosys submodule with the latest yosys changes. Most significant one is adder mode is now default.
=> Bumping up latest yosys changes to yosys submodule

openfpga_flow/benchmarks/quicklogic_tests/shift_reg_8192/rtl/shift_reg_8192.v
Add a new test case for shift register mode 
- [X ] Require new tests to be added
=> add shift register test case

.github/workflows/build.yml, openfpga/src/annotation/write_xml_device_rr_gsb.cpp
This PR enhances data dumped by the `write_gsb_to_xml` by including rr graph node indices.
=> GSB dump enhancement

docs/source/tutorials/getting_started/compile.rst
=> Updated compile.rst

openfpga_flow/vpr_arch/k4_frac_N8_tileable_reset_softadder_register_scan_chain_dsp8_nonLR_caravel_io_skywater130nm.xml, openfpga_flow/vpr_arch/k4_frac_N8_tileable_reset_softadder_register_scan_chain_frac_dsp16_nonLR_caravel_io_skywater130nm.xml, vpr/src/tileable_rr_graph/tileable_rr_graph_gsb.cpp
> - [X] To address an existing issue. If so, please provide a link to the issue: #300 
> 
> 
> 
> 
> 
> To address issue #300
>
> 
> 
> After a careful inspection, the tileable rr_graph generator has no problems in creating nodes and edges for these input pins on the top side of a multi-height block. The actual problem is that VPR's architecture description language requires a specific ``yoffset=<int>`` for each side segment of a multi-width and multi-height block. By default, the offset is always zero, causing that the pin …
=> Tileable rr graph

docs/source/manual/file_formats/index.rst, docs/source/manual/file_formats/io_mapping_file.rst, docs/source/manual/openfpga_shell/openfpga_commands/fpga_bitstream_commands.rst, openfpga/src/base/io_map.cpp, openfpga/src/base/io_map.h, openfpga/src/base/io_map_fwd.h, openfpga/src/base/openfpga_bitstream.cpp, openfpga/src/base/openfpga_bitstream.h, openfpga/src/base/openfpga_bitstream_command.cpp, openfpga/src/fpga_bitstream/build_io_mapping_info.cpp, openfpga/src/fpga_bitstream/build_io_mapping_info.h, openfpga/src/fpga_bitstream/write_xml_io_mapping.cpp, openfpga/src/fpga_bitstream/write_xml_io_mapping.h, openfpga_flow/openfpga_shell_scripts/write_io_mapping_example_script.openfpga, openfpga_flow/regression_test_scripts/fpga_bitstream_reg_test.sh, openfpga_flow/tasks/fpga_bitstream/write_io_mapping/config/task.conf
> 
> 
> Currently, OpenFPGA has the following limitations:
> - [X] I/O mapping information are covered in internal data structures, which causes difficulties for end-users to know which I/O pin is mapped to which net. 
>
> 
> 
> This PR improves in the following aspects:
> - [X] Add a new command 'write_io_mapping' to openfpga shell which can output I/O pin-to-net mapping to an XML-based file format.
Here is an example file that is …
=> Output I/O mapping information to XML file

.github/workflows/build.yml, openfpga_flow/benchmarks/micro_benchmark/and4/and4.v, openfpga_flow/benchmarks/micro_benchmark/counter_128bit_async_reset/counter.v, openfpga_flow/benchmarks/micro_benchmark/counter_128bit_async_reset/counter_tb.v, openfpga_flow/benchmarks/micro_benchmark/counter_128bit_async_resetb/counter.v, openfpga_flow/benchmarks/micro_benchmark/counter_128bit_async_resetb/counter_tb.v, openfpga_flow/benchmarks/micro_benchmark/mac/mac_18/mac_18.v, openfpga_flow/benchmarks/micro_benchmark/mac/mac_20/mac_20.v, openfpga_flow/benchmarks/micro_benchmark/mac/mac_36/mac_36.v, openfpga_flow/benchmarks/micro_benchmark/mac/mac_8_9/mac_8_9.v, openfpga_flow/benchmarks/micro_benchmark/mac/mac_9/mac_9.v, openfpga_flow/openfpga_shell_scripts/mcnc_example_script.openfpga, openfpga_flow/regression_test_scripts/fpga_verilog_reg_test.sh, openfpga_flow/regression_test_scripts/micro_benchmark_reg_test.sh, openfpga_flow/tasks/benchmark_sweep/counter/config/task.conf, openfpga_flow/tasks/benchmark_sweep/mac_units/config/task.conf
> 
> 
>
> 
> 
> 
> - [ ] VPR
> - [x] …
=> Micro benchmark

openfpga_flow/scripts/run_fpga_task.py, openfpga_flow/tasks/basic_tests/global_tile_ports/global_tile_4clock/config/task.conf
> - [x] To address an existing issue. If so, please provide a link to the issue: <issue id>
> 
> 
> 
> 
> 
Address issue #357 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR
> - [x] Regression tests
> ### …
=> Testcase for benchmark specific variables

openfpga_flow/misc/ys_tmpl_yosys_vpr_dsp_flow.ys
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR …
=> replace opt_rmdff

openfpga_flow/tasks/quicklogic_tests/flow_test/config/task.conf
Currently only the basic test case (counter) is enabled in Quicklogic Regression.
This PR will enable all the applicable tests in the regression.
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
Adds previously running tests back into the quicklogic regression suite
> 
> - [ ] VPR
> - [ …
=> Enable all quicklogic tests

libs/EXTERNAL/libargparse/src/argparse.cpp
Include is missing.
Add missing include in `libs/EXTERNAL/libargparse/src/argparse.cpp`
=> Address: Compilation fails on Manjaro

.github/workflows/build.yml, docs/source/contact.rst
> - [ ] To address an existing issue. If so, please provide a link to the issue: #421 #429
> - [ ] Breaking new feature. If so, please describe the details in the description part.
Fixes the yosys paths to copy in docker image
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR
> - [ ] Continous …
=> Updated yosys paths to copy in docker image

.dockerignore
> - [ ] To address an existing issue. If so, please provide a link to the issue: #421 #429
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR …
=> Fixed missing yosys share directory

.github/dependabot.yml
Use dependabot to create PRs automatically when yosys-symbiflow-plugins is updated.
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
Adds dependabot yaml configuration to update yosys-plugins
> 
> - [ ] VPR
> - [ ] Architecture …
=> Automatic PR creation for yosys-symbiflow-plugins update

openfpga/src/fpga_bitstream/build_grid_bitstream.cpp
> Currently Bitstream annotation from external XML only works for LUTs
> Change the mode bitstream setting code for Hard block primitives to override bitstream if there is annotation 
> 
> - [ ] VPR
> - [X ] OpenFPGA libraries
> - [ ] …
=> allow bitstream setting  on hard blocks

.github/dependabot.yml
> 
> 
- Yosys integration is manually done.
> 
>
> 
> 
> 
> 
> - [ ] VPR
> - [ ] Cell …
=> Enable Yosys in dependabot

.github/workflows/patch_updater.yml
> - [x ] To address an existing issue. If so, please provide a link to the issue: #442 
> 
> - [ ] VPR
> - [x ] Flow scripts
=> Added Auto PR step

docs/source/dev_manual/index.rst, docs/source/dev_manual/version_number.rst
> 
> 
- We have set up the automate update on version numbers. But no documentation about our versioning strategy.
>
> 
> 
> 
> 
> - [ ] VPR
> - [ ] …
=> Add version naming convention to developer guidelines

docs/source/manual/openfpga_flow/run_fpga_task.rst, openfpga_flow/scripts/run_fpga_task.py, openfpga_flow/tasks/basic_tests/explicit_multi_verilog_files/config/task.conf, openfpga_flow/tasks/basic_tests/k4_series/k4n4_bram/config/task.conf, openfpga_flow/tasks/basic_tests/k4_series/k4n4_fracff/config/task.conf, openfpga_flow/tasks/benchmark_sweep/counter/config/task.conf, openfpga_flow/tasks/benchmark_sweep/iwls2005/config/task.conf, openfpga_flow/tasks/benchmark_sweep/mac_units/config/task.conf, openfpga_flow/tasks/benchmark_sweep/vtr_benchmarks/config/task.conf, openfpga_flow/tasks/fpga_bitstream/generate_bitstream/device_48x48/config/task.conf, openfpga_flow/tasks/fpga_verilog/bram/dpram1k/config/task.conf, openfpga_flow/tasks/fpga_verilog/bram/wide_dpram1k/config/task.conf, openfpga_flow/tasks/fpga_verilog/dsp/multi_mode_mult_16x16/config/task.conf, openfpga_flow/tasks/fpga_verilog/dsp/single_mode_mult_8x8/config/task.conf, openfpga_flow/tasks/fpga_verilog/dsp/single_mode_mult_8x8_reg/config/task.conf, openfpga_flow/tasks/fpga_verilog/dsp/wide_multi_mode_mult_16x16/config/task.conf, openfpga_flow/tasks/quicklogic_tests/counter_5clock_test/config/task.conf, openfpga_flow/tasks/quicklogic_tests/flow_test/config/task.conf, openfpga_flow/tasks/quicklogic_tests/lut_adder_test/config/task.conf
> - [x] To address an existing issue. If so, please provide a link to the issue: #489 
- Updated `run_fpga_task.py` script to handle Synthesis section common configs.
- Updated task configurations
- Updated documentation
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR
> - [ ] …
=> Moved 'verific_*' and 'yosys_*' config options from 'OpenFPGA_SHELL' to 'Synthesis Parameter' sections.

openfpga/src/fpga_verilog/verilog_top_testbench.cpp
> - [x] To address an existing issue. If so, please provide a link to the issue: [https://github.com/lnis-uofu/OpenFPGA/issues/428#issuecomment-997826399](url)
> ccff_head signal is unknown
> 
> 
> 
> 
> 
>
> fixes that problem and successfully download bitstream to the fpga
> 
> 
> 
> 
> 
> 
> - [ ] VPR …
=> changing condition of bitstream downloading

.github/workflows/patch_updater.yml
> 
> 
> 
> 
> 
>
> 
> 
> 
> - [ ] VPR
> - [x] Continous Integration (CI) …
=> [CI] Update patch updater due to release v1.1.0

vpr/src/base/netlist_writer.cpp, vpr/src/base/netlist_writer.h
> 
> <Post layout netlist and SDF generation for black box module is broken in VPR netlist writer code in OpenFPGA. This has already been fixed in VPR master>
>
> 
> <Bring in latest changes from VPR to fix post layout netlist write and SDF geneartio>
> 
> 
> - [X] VPR …
=> Merge fixes for post layout netlist/sdf generation for blackbox modules

docs/source/manual/arch_lang/addon_vpr_syntax.rst
> - [x] To address an existing issue. If so, please provide a link to the issue: <issue id>
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR …
=> Fix a small typo to trigger the CI flow.

Dockerfile, README.md
**[Binder](https://mybinder.org/)** creates a temporary custom work environment on the cloud to allow a remote user to execute and evaluate the code. Now users can click on the Binder button in the README section and launch a pre-compiled environment to evaluate and develop OpenFPGA flow. I used a docker image updated by the OpenFPGA repo with every master merge and extended that to work with the Binder environment.
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR
> - …
=> Added Binder interface

openfpga.sh, openfpga_flow/regression_test_scripts/basic_reg_test.sh, openfpga_flow/tasks/template_tasks/vtr_benchmarks_template/config/task.conf, openfpga_flow/tasks/template_tasks/vtr_benchmarks_template/k6_N10_tileable_dpram8K_dsp36_40nm.xml, openfpga_flow/tasks/template_tasks/vtr_benchmarks_template/k6_frac_N10_tileable_adder_chain_dpram8K_dsp36_40nm.xml, openfpga_flow/tasks/template_tasks/vtr_benchmarks_template/vtr_benchmark_template_script.openfpga, openfpga_flow/vpr_arch/k6_N10_tileable_adder_chain_dpram8K_dsp36_40nm.xml
Added minor enhancements in openfpga.sh 
- list-task can list all repository tasks, irrespective of the current working directory
- create_task auto-completes  template tasks
Added VPR7.0 flagship architecture without fracturable-lut for experiments.
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR
> - [ ] Regression …
=> Minor enhancements in openfpga.sh script

.github/workflows/install_dependencies_run.sh, docker/Dockerfile.master
Currently, the docker image created as a part of each main merge does not contain any user, all the packages inside the docker image is installed with the root permission, this creates a problem while integrating this with other tools.
This PR adds an explicit user to the docker image
> - [ ] Breaking new feature. If so, please describe the details in the description part.
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR
> - …
=> Added user to the docker image

.github/workflows/build.yml
Force docker based regression test as a root user
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR
> - [ ] Continous …
=> Fixing docker based regression test

docker/Dockerfile.master
**Fixing bug in dockerfile**
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR …
=> [Bugfix] dockerfile

docs/source/tutorials/getting_started/compile.rst
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR …
=> Update compile.rst to avoid confusion in https://github.com/lnis-uofu/OpenFPGA/issues/724

.dockerignore
@tangxifan Docker build fixed with [this commit ](https://github.com/lnis-uofu/OpenFPGA/commit/02dd01329922b3c9c5a9c293d957cc3f99fedbb1); there are still some regression errors.
Let me know if that's because of the infrastructure, and I will look into it.
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR
> - [ ] …
=> [CiFix] Docker image

docs/source/manual/openfpga_shell/openfpga_commands/setup_commands.rst, openfpga/src/annotation/rr_gsb_writer_option.cpp, openfpga/src/annotation/rr_gsb_writer_option.h, openfpga/src/annotation/write_xml_device_rr_gsb.cpp, openfpga/src/annotation/write_xml_device_rr_gsb.h, openfpga/src/base/openfpga_setup_command.cpp, openfpga/src/base/openfpga_write_gsb.cpp, openfpga_flow/regression_test_scripts/basic_reg_test.sh, openfpga_flow/tasks/basic_tests/write_gsb/write_gsb_to_xml_exclude_cbx/config/task.conf, openfpga_flow/tasks/basic_tests/write_gsb/write_gsb_to_xml_exclude_cbx_cby/config/task.conf, openfpga_flow/tasks/basic_tests/write_gsb/write_gsb_to_xml_exclude_cby/config/task.conf, openfpga_flow/tasks/basic_tests/write_gsb/write_gsb_to_xml_exclude_rr_info/config/task.conf, openfpga_flow/tasks/basic_tests/write_gsb/write_gsb_to_xml_exclude_sb/config/task.conf, openfpga_flow/tasks/basic_tests/write_gsb/write_gsb_to_xml_exclude_sb_cbx/config/task.conf, openfpga_flow/tasks/basic_tests/write_gsb/write_gsb_to_xml_exclude_sb_cby/config/task.conf, openfpga_flow/tasks/basic_tests/write_gsb/write_gsb_to_xml_include_sb_cbx_cby/config/task.conf, openfpga_flow/tasks/basic_tests/write_gsb/write_gsb_to_xml_include_single_cbx/config/task.conf, openfpga_flow/tasks/basic_tests/write_gsb/write_gsb_to_xml_include_single_cby/config/task.conf, openfpga_flow/tasks/basic_tests/write_gsb/write_gsb_to_xml_include_single_sb/config/task.conf
> 
> 
- It is hard to compare GSB files (to see if how identical GSBs are) as it contains 
- the connections in SBs, CBx and CBy in one file
- the rr_graph information, such as node id, which is very different from one GSB to another. However, these information will not impact the graph matching results, which is used to find unique modules.
>
> 
> 
This PR improves in the following …
=> Enhanced GSB writer with more flexibility

openfpga/src/fabric/build_top_module.cpp, openfpga_flow/regression_test_scripts/basic_reg_test.sh, openfpga_flow/scripts/io_sequence_visualizer.py, openfpga_flow/tasks/basic_tests/k4_series/k4n4_custom_io_loc_center/config/task.conf, openfpga_flow/tasks/basic_tests/k4_series/k4n4_custom_io_loc_center_height_odd/config/task.conf, openfpga_flow/tasks/basic_tests/k4_series/k4n4_custom_io_loc_center_width_odd/config/task.conf, openfpga_flow/vpr_arch/k4_N4_tileable_customIoLoc_40nm.xml
> 
> 
> 
> 
> 
>
> 
> 
> 
> - [ ] VPR …
=> Now I/O indexing follows a natural way (clockwise) throughout the fabric.

README.md
+ Tagged final build of v1.1 as Final1.1
+ Instruction to access last build of v1.1
+ Added instructions for arch file upgrade
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR
> ### Impact of the pull request
> - [ ] Require a change on Quality of …
=> Updated readme, breaking changes in v1.2, and instruction to use v1.1

.github/workflows/build.yml, .github/workflows/cell_lib_test.yml, .github/workflows/docker.yml, .github/workflows/format.yaml, .github/workflows/install_dependencies_build.sh, .github/workflows/install_dependencies_run.sh, docker/Dockerfile.base, docker/Dockerfile.env, docker/Dockerfile.gcc-10, docker/Dockerfile.gcc-11
> - [x] To address an existing issue. If so, please provide a link to the issue: #832 
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR …
=> [ci] update docker image from ubuntu 18.04 to 20.04

.github/workflows/build.yml, .github/workflows/doc_dependencies.sh, .github/workflows/install_dependencies_build_ubuntu22p04.sh, docs/source/tutorials/getting_started/compile.rst, docs/source/tutorials/getting_started/doc_dependencies.sh, docs/source/tutorials/getting_started/regtest_dependencies.sh, docs/source/tutorials/getting_started/ubuntu20p04_dependencies.sh, docs/source/tutorials/getting_started/ubuntu22p04_dependencies.sh
> 
> 
- CI does not cover Ubuntu 22.04 
- 
> 
> 
> 
> - [ ] VPR
> - …
=> Ubuntu22p04 support

Makefile, docs/source/tutorials/getting_started/compile.rst
> 
> 
- ``make compile`` does not work
>
> 
> 
> 
> - [ ] VPR
> - [ …
=> Now make compile should work well

docs/source/appendix/figures/rapidflex_logo.png:Zone.Identifier
> - [x] To address an existing issue. If so, please provide a link to the issue: #990 
> 
> 
> 
> 
> 
>
> 
> 
This PR improves in the following aspects
> 
> - [ ] VPR …
=> [doc] remove temp files

openfpga_flow/benchmarks/micro_benchmark/mult/mult16/mult16.v, openfpga_flow/benchmarks/micro_benchmark/mult/mult8/mult8.v, openfpga_flow/misc/ys_tmpl_yosys_vpr_dsp_flow.ys, openfpga_flow/misc/ys_tmpl_yosys_vpr_dsp_flow_with_rewrite.ys, openfpga_flow/openfpga_arch/k4_N4_frac_dsp16_40nm_cc_openfpga.xml, openfpga_flow/openfpga_yosys_techlib/k4_N4_tileable_frac_dsp16_40nm_cell_sim.v, openfpga_flow/openfpga_yosys_techlib/k4_N4_tileable_frac_dsp16_40nm_dsp_map.v, openfpga_flow/regression_test_scripts/fpga_bitstream_reg_test.sh, openfpga_flow/tasks/fpga_bitstream/overload_dsp_mode_bit/config/bitstream_annotation.xml, openfpga_flow/tasks/fpga_bitstream/overload_dsp_mode_bit/config/task.conf, openfpga_flow/vpr_arch/k4_N4_tileable_frac_dsp16_40nm.xml
> - [x] To address an existing issue. If so, please provide a link to the issue: #443 
> 
> 
> 
> 
> 
>
> 
> 
> 
> - [ ] VPR …
=> Rework PR #443

.github/workflows/build.yml, CMakeLists.txt, Makefile, docs/source/tutorials/getting_started/compile.rst, openfpga/CMakeLists.txt, openfpga/src/annotation/annotate_clustering.cpp, openfpga/src/annotation/annotate_clustering.h, openfpga/src/base/openfpga_link_arch_template.h, openfpga/src/fpga_verilog/verilog_top_testbench.cpp, openfpga/src/utils/lut_utils.cpp
> - [x] To address an existing issue. If so, please provide a link to the issue: #832 
> 
> 
> 
> 
> 
>
> 
> 
> 
> - [ ] VPR …
=> More build tests: debug and no warnings

.github/workflows/build.yml, .github/workflows/install_dependencies_run_ubuntu22p04.sh
> 
> 
> 
> 
- See some failures on ccache when using self-hosted machine for debug and no-warning build. 
>
> 
> 
> 
> 
> 
> - [ ] VPR
> - [ …
=> [ci] now use github machine for debug build and no warnings

Dockerfile
During OpenFPGA upgrade the docker image package creation is changed and created conflict with the the docker file used for the binder session. This PR fix those discrepancies.
**It is standalone change only for binder run and it should not affect any regression of build system.** 
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR
> - [ ] …
=> Fixing binder dockerfile

Dockerfile
Follow up PR, fixed binder docker. Jupyter-hub installation process
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR
> …
=> Updating binder dockers

openfpga_flow/scripts/run_fpga_flow.py, openfpga_flow/scripts/run_fpga_task.py
1. During the upgrade process, some parts of the *_task.py changes, which caused duplicated columns to be created in the.csv file
This PR fixes that problem. 
2. Fixed default variables paths like ``OPENFPGA_SHELLSCRIPT_PATH`` and  ``ARCH_PATH`` fixed that
3. 
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR
> - [ …
=> Refactor run_fpga_task.py and run_fpga_flow.py

docs/source/manual/file_formats/clock_network.rst
> 
> 
> 
> 
See broken links in the online documentation.
>
> 
> 
> 
> - [ ] VPR
> - [ ] …
=> [doc] fix broken links in the Clock Network file format

.github/workflows/build.yml, Makefile
> 
> 
- ``make all`` failed on CI as ``make checkout`` is executed in parallel to the ``make compile``
>
> 
> 
> 
> - [ ] VPR
> - [ ] Flow …
=> [script] serialize make all depedent targets to avoid ``make all`` bugs

openfpga_flow/misc/ys_tmpl_yosys_vpr_adder_flow.ys, openfpga_flow/openfpga_yosys_techlib/openfpga_adders_sim.v, openfpga_flow/openfpga_yosys_techlib/openfpga_arith_map.v, openfpga_flow/scripts/run_fpga_task.py, openfpga_flow/tasks/fpga_verilog/adder/hard_adder/config/dummy_pin_constraints.xml, openfpga_flow/tasks/fpga_verilog/adder/hard_adder/config/task.conf
> - [x] To address an existing issue. If so, please provide a link to the issue: #976
> 
> 
- As stated in #976 
>
> 
> 
> 
> - [ ] VPR
> - …
=> Enable Adder mapping and validation on FPGA architecture using hard adders

Dockerfile
Binder execution was broken because of outdated dependencies, fixed by updating the docker file.
@AllenDBoston 
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR
> - …
=> Fixed binder dependencies

openfpga_flow/openfpga_shell_scripts/group_config_block_full_testbench_example_script.openfpga, openfpga_flow/regression_test_scripts/basic_reg_test.sh, openfpga_flow/tasks/basic_tests/group_config_block/group_config_block_hetero_fabric_tile_Lshape/config/task.conf, openfpga_flow/tasks/basic_tests/group_config_block/group_config_block_hetero_fabric_tile_Lshape/config/tile_config.xml, openfpga_flow/tasks/basic_tests/group_config_block/group_config_block_homo_Lshape_full_testbench/config/task.conf, openfpga_flow/tasks/basic_tests/group_config_block/group_config_block_homo_fabric_tile/config/task.conf, openfpga_flow/tasks/basic_tests/group_config_block/group_config_block_homo_fabric_tile_core_wrapper/config/task.conf, openfpga_flow/vpr_arch/k4_N4_tileableL_40nm.xml, openfpga_flow/vpr_arch/k4_frac_N8_tileableL_reset_softadder_register_scan_chain_dsp8_nonLR_caravel_io_skywater130nm.xml
> 
> 
> 
> 
> 
>
> 
> 
> 
> - [ ] VPR …
=> Upgrade VTR to the latest: Introduce new feature ``shrink_boundary`` for tileable routing 

docs/source/manual/index.rst, docs/source/manual/utilities/fabric_key_assistant.rst, docs/source/manual/utilities/index.rst, libs/libfabrickey/CMakeLists.txt, libs/libfabrickey/src/base/fabric_key.cpp, libs/libfabrickey/src/base/fabric_key.h, libs/libfabrickey/src/utils/check_fabric_key.cpp, libs/libfabrickey/src/utils/check_fabric_key.h, libs/libfabrickey/test/fabric_key_assistant.cpp
> 
> 
```
Fabric key is an important feature of OpenFPGA, which allows chip designers to customize the configuration scheme for each programmable resource. Fabric key describes how the programmable resources are connected to a configuration protocol, for example, how BL/WLs are shared between tiles. Note that fabric key is typically in a strong need of hand crafting, as its content strongly impacts the QoR of physical design. …
```
=> Add a utility tool: fabric key assistant

.readthedocs.yml
See the logs from readthedocs build:
This is blocking #1329 #1328 #1327 
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR
> - [ ] Regression …
=> Update .readthedocs.yml by removing deprecated syntax

.readthedocs.yml, docs/requirements.txt
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR …
=> Update .readthedocs.yml to check if python version causes build failures.

docs/requirements.txt
> 
> 
- Doc build error is seen at readthedocs.com (See screenshot below). The root of cause is that the python package ``sphinx-rtd-scheme`` is no longer installed by default on readthedocs builder.
>
> 
> 
> 
> - [ ] VPR
> - [ ] OpenFPGA …
=> [doc] add missing packages

.github/labeler.yml
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR …
=> [ci] format labeler

openfpga/src/base/openfpga_pb_pin_fixup.cpp
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR …
=> [core] fixed a bug where pb pin fixup may fail when subtile capacities are not same

openfpga_flow/scripts/arch_file_updater.py, openfpga_flow/scripts/io_sequence_visualizer.py, openfpga_flow/scripts/run_fpga_flow.py, requirements.txt
> - [x] To address an existing issue. If so, please provide a link to the issue: #1602 
> 
> 
> 
> 
> 
As addressed in #1602 
>
> 
> 
- update black version requirement from 20.8b1 to 24.3.0
- Reformat python codes
> 
> - [ ] VPR
> …
=> update black version from 20.8b1 to 24.3.0

docker/Dockerfile.env
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR …
=> [docker] fix bugs on python3

openfpga_flow/regression_test_scripts/basic_reg_test.sh, openfpga_flow/regression_test_scripts/basic_reg_yosys_only_test.sh, openfpga_flow/regression_test_scripts/fpga_bitstream_reg_test.sh, openfpga_flow/regression_test_scripts/fpga_sdc_reg_test.sh, openfpga_flow/regression_test_scripts/fpga_spice_reg_test.sh, openfpga_flow/regression_test_scripts/fpga_verilog_reg_test.sh, openfpga_flow/regression_test_scripts/iwls_benchmark_reg_test.sh, openfpga_flow/regression_test_scripts/micro_benchmark_reg_test.sh, openfpga_flow/regression_test_scripts/quicklogic_reg_test.sh, openfpga_flow/regression_test_scripts/vtr_benchmark_reg_test.sh
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR …
=> [test] now use latest python3 of ubuntu 22.04

openfpga/src/base/openfpga_link_arch_template.h, openfpga_flow/openfpga_shell_scripts/preload_rr_graph_example_script.openfpga, openfpga_flow/regression_test_scripts/basic_reg_test.sh, openfpga_flow/tasks/basic_tests/preload_rr_graph/preload_rr_graph_bin/config/task.conf, openfpga_flow/tasks/basic_tests/preload_rr_graph/preload_rr_graph_xml/config/task.conf
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR …
=> [core] fixed a bug where incoming edges are not built after loading rr_graph in vpr

.github/workflows/build.yml, .github/workflows/cell_lib_test.yml, .github/workflows/format.yaml, .github/workflows/patch_updater.yml
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR …
=> bring back reg tests on master branch and version updater is now triggered automatically on any changes to master branch

docs/source/manual/file_formats/tile_config_file.rst
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR …
=> [doc] format to resolve latexpdf build errors; now local build passes

openfpga/src/annotation/openfpga_annotate_routing.cpp, openfpga/src/annotation/route_clock_rr_graph.cpp
…sabled
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR
> ### Impact of …
=> [core] fixed a bug where unused last-level of clock spines are not disabled

openfpga/src/annotation/route_clock_rr_graph.cpp
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR …
=> [core] fixed a bug where some clock spine was wrongly marked unused

openfpga/src/vpr_wrapper/vpr_main.cpp
> - [X] To address an existing issue. If so, please provide a link to the issue: <#1821>
> #### What is currently done? (Issue link: https://github.com/lnis-uofu/OpenFPGA/issues/1821)
> Currently there is a typo in the completion message for vpr
> Fixed typo
> 
> - [ ] VPR
> - [X] Flow scripts …
=> Fixed typo in vpr-main.cpp

.github/workflows/build.yml, CMakeLists.txt, libs/libopenfpgacapnproto/CMakeLists.txt
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR …
=> [core] unique block capn will update only on demand

.github/workflows/build.yml, CMakeLists.txt, Makefile, cmake/modules/OpenfpgaInstaller.cmake, cmake/modules/OpenfpgaPackaging.cmake, docs/source/tutorials/getting_started/compile.rst, libs/libarchopenfpga/CMakeLists.txt, libs/libbusgroup/CMakeLists.txt, libs/libclkarchopenfpga/CMakeLists.txt, libs/libfabrickey/CMakeLists.txt, libs/libfpgabitstream/CMakeLists.txt, libs/libini/CMakeLists.txt, libs/libnamemanager/CMakeLists.txt, libs/libopenfpgashell/CMakeLists.txt, libs/libopenfpgautil/CMakeLists.txt, libs/libpcf/CMakeLists.txt, libs/libtileconfig/CMakeLists.txt, openfpga/CMakeLists.txt
> 
> 
- User can only build from source codes. This enforces a high tech bar for entry-level engineers.
>
> 
> 
> 
> - [ ] VPR
> - [ ] Flow …
=> CPack-based Installer

libs/libclkarchopenfpga/src/io/write_xml_clock_network.cpp, openfpga_flow/openfpga_shell_scripts/example_clkntwk_no_ace_script.openfpga
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] VPR …
=> use pugi xml in clock network writer

.github/workflows/build.yml
> - [x] To address an existing issue. If so, please provide a link to the issue: #2157 
> 
> 
> 
> 
> 
>
> 
> 
> 
> - [ ] VPR
> - [x] Continous Integration (CI) …
=> [ci] enable quick test on Ubunut 24.04
